<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tooltip-txt_my-shares</name>
   <tag></tag>
   <elementGuidId>6bb0283d-feb7-4cf7-89a2-18a02553d773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popper_28k7lwwe_7e8s3a']/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'This total includes all shares issued to you, both conditional and unconditional. Note: Exercised options are counted as unconditional shares.' or . = 'This total includes all shares issued to you, both conditional and unconditional. Note: Exercised options are counted as unconditional shares.')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-popper__inner > div > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='popper_28k7lwwe_7e8s3a']/div[2]/div/div/div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97ff6f14-4bf5-4ee7-ae8b-dd08c6b8ec86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This total includes all shares issued to you, both conditional and unconditional. Note: Exercised options are counted as unconditional shares.</value>
      <webElementGuid>93bcd8f2-5105-4b3a-b7a8-417b8b862f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popper_28k7lwwe_7e8s3a&quot;)/div[@class=&quot;v-popper__wrapper&quot;]/div[@class=&quot;v-popper__inner&quot;]/div[1]/div[1]</value>
      <webElementGuid>c16e33ad-ace0-4e2b-ad26-8f537b8eab1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popper_28k7lwwe_7e8s3a']/div[2]/div/div/div</value>
      <webElementGuid>83aac8b3-0ddf-4890-8444-d29a3895880d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave feedback'])[1]/following::div[6]</value>
      <webElementGuid>085f43e4-3922-4534-9eaf-4f1e2a1477ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[1]/following::div[6]</value>
      <webElementGuid>7700e478-90cb-42f8-94a4-1ed1cd2ffad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>d14cf23c-bf2c-4a37-b6de-3d3716c2f1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'This total includes all shares issued to you, both conditional and unconditional. Note: Exercised options are counted as unconditional shares.' or . = 'This total includes all shares issued to you, both conditional and unconditional. Note: Exercised options are counted as unconditional shares.')]</value>
      <webElementGuid>05574850-5519-4f7b-9b27-1bd5eca73174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
