<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_must sign</name>
   <tag></tag>
   <elementGuidId>51456452-e83d-4804-b2c8-891a0582cea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/h1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@name, 'must_sign_applies')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a235209a-a0ca-4dec-b531-e1064d2750bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>must_sign_applies</value>
      <webElementGuid>19cd03ed-0835-43b9-aea1-4cfad9fabd0d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
