<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Existing authorisation status</name>
   <tag></tag>
   <elementGuidId>84110f2f-1145-4a3a-b01a-3cfc0b187242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/form/div/div[4]/div/h5[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.width-500 > h5:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>870ddfc9-7c5c-401b-9a9b-e956321c17bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Existing authorisation status</value>
      <webElementGuid>39ff7c2c-e8bd-4348-bfd7-f73cf6c2abcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[4]/div[@class=&quot;width-500&quot;]/h5[2]</value>
      <webElementGuid>13714bed-72e3-42d6-b0c9-d3a4b4270c70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[4]/div/h5[2]</value>
      <webElementGuid>e3355b9f-97e9-405c-aee2-f43f54fdff17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Existing authorisation status']/parent::*</value>
      <webElementGuid>338bdeb5-2b80-463d-9add-62df60dfb5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/h5[2]</value>
      <webElementGuid>9990966b-cb0f-4abb-9f2e-941f9d61f6dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Existing authorisation status' or . = 'Existing authorisation status')]</value>
      <webElementGuid>d84acca2-7edf-44b4-8233-baccebc1eb42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
