<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Knowledge level_otfDO8wisc75PuRZ</name>
   <tag></tag>
   <elementGuidId>58340afb-c278-400b-b6f5-c7a10c500bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otfDO8wisc75PuRZ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otfDO8wisc75PuRZ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fa85783-e960-41d2-9c68-3f5af82770f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>392320f8-502e-4d39-9bca-ad7df1d2d0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-search</value>
      <webElementGuid>9f74eb65-5b15-43c1-9867-e3451fd8882a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otfDO8wisc75PuRZ</value>
      <webElementGuid>5dcaef4a-5633-4f05-b8ff-df7d04d84736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>otfDO8wisc75PuRZ-multiselect-options</value>
      <webElementGuid>6cb8fb1c-384e-4f68-bc7e-4f70d857f1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8da46f27-5fc7-4418-a72c-c45240c6a242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1933455-f151-439d-84ce-dc5788103631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>94e7870f-ca7a-462e-ac54-28d60a541fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>otfDO8wisc75PuRZ-assist</value>
      <webElementGuid>93050548-b038-4cd5-9dbc-7ebe9da2c8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otfDO8wisc75PuRZ&quot;)</value>
      <webElementGuid>442802f3-cf44-4641-8e80-27514cfc0a8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otfDO8wisc75PuRZ']</value>
      <webElementGuid>6fceec59-f63c-481d-a418-eeb5a8d9f7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[6]/div[9]/div/div/div/input</value>
      <webElementGuid>a3a0d727-259a-4570-9abd-dd19086a106a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/input</value>
      <webElementGuid>3a1dcff8-3f04-4ef9-9162-41f164a44f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'otfDO8wisc75PuRZ']</value>
      <webElementGuid>275f8cd6-e189-4e1b-b211-ba700cd5a8f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
