<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AML risk score (1-4)_YfPa4S2O6TwYXV3V</name>
   <tag></tag>
   <elementGuidId>a932ec88-35f8-441b-b8d2-746ead53b200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='YfPa4S2O6TwYXV3V']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#YfPa4S2O6TwYXV3V</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96b9a5ea-9d57-44ed-a720-1a16cedab48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62b9dd21-5ac8-484a-9303-2b53f5df449e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-search</value>
      <webElementGuid>f998fd7f-4c85-4588-a8d3-d29486a7a811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>YfPa4S2O6TwYXV3V</value>
      <webElementGuid>3facc4d6-703d-426e-bcd8-241b328e044b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>YfPa4S2O6TwYXV3V-multiselect-options</value>
      <webElementGuid>10cd805c-d306-4c37-90c5-b81ce325b934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3873a830-2a0d-42ad-b738-93f2dd0b8d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e64aa002-8d3e-4bd3-a339-00e154a11df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>47a2cc6f-ef7c-495d-801b-4101f42f08ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>YfPa4S2O6TwYXV3V-assist</value>
      <webElementGuid>21c0c91e-d4c5-4d93-be38-6d5513b3dbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YfPa4S2O6TwYXV3V&quot;)</value>
      <webElementGuid>24283371-6aaf-422e-aacf-6d5388746d44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='YfPa4S2O6TwYXV3V']</value>
      <webElementGuid>6bb681f3-6e66-4ea1-8add-56f12ed4b9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[6]/div[9]/div[2]/div/div/input</value>
      <webElementGuid>ffb8400c-abfe-4a00-8b21-7a9207b419b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/input</value>
      <webElementGuid>ff2ce912-68b8-4a0f-825e-b4cb1aafb1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'YfPa4S2O6TwYXV3V']</value>
      <webElementGuid>5fc78b60-8fb0-4519-91c2-af03376e4f50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
