<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Migration process_detailshandover_inf_c61b81</name>
   <tag></tag>
   <elementGuidId>0c2e69c3-f8a7-4755-abce-7714b3e9d8f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Z3eDbfIheaxzOone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Z3eDbfIheaxzOone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05bbaacc-df02-4fd0-b5d9-8297663d67e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f2c55e72-7da0-453e-9710-9b5c73d37f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fbd671df-c75d-45b2-8023-36bcfb0f4042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Z3eDbfIheaxzOone</value>
      <webElementGuid>b53c85f0-0c43-49a0-9355-328dea52f03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details[handover_info][existing_scheme_upload][migration_process]</value>
      <webElementGuid>1e6279d6-b091-4cae-a619-0b127126ca4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Z3eDbfIheaxzOone&quot;)</value>
      <webElementGuid>097358b3-d16c-4aee-829d-85ce8d43927d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Z3eDbfIheaxzOone']</value>
      <webElementGuid>834befe3-bf81-4f4b-9ea1-bacfe7ecf41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[2]/div/div[6]/div/input</value>
      <webElementGuid>a042e7ca-d0b0-4058-b450-a01eedf42a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>92c1249a-4ab4-4ce6-a918-e01c69d24782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Z3eDbfIheaxzOone' and @name = 'details[handover_info][existing_scheme_upload][migration_process]']</value>
      <webElementGuid>2abc1d4d-2b3d-4eb4-86c5-455dfa642e65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
