<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do they have a Shareholders Agreement_b2b5e2</name>
   <tag></tag>
   <elementGuidId>a8e8a6e6-e958-4e90-9040-4406883da90d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='details[handover_info][articles_and_governance][existing_shareholder_agreements]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;details[handover_info][articles_and_governance][existing_shareholder_agreements]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbada58d-841b-4429-98b7-2b07657b3852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>310db7aa-3e2a-46ec-82eb-d5490e6f9d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-1</value>
      <webElementGuid>6fe3c20b-a00a-42d6-8ba6-2e17194ac6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details[handover_info][articles_and_governance][existing_shareholder_agreements]</value>
      <webElementGuid>00c69301-2369-413b-a7d3-85d6bdd7c1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>10ec2b19-269c-4993-b0f1-4c50d05d5f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[4]/div[@class=&quot;width-500&quot;]/div[@class=&quot;form-group mb-3&quot;]/div[@class=&quot;mb-3&quot;]/label[@class=&quot;font-weight-normal&quot;]/input[@class=&quot;mr-1&quot;]</value>
      <webElementGuid>dc8c2369-9bf0-4459-a013-454161866518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='details[handover_info][articles_and_governance][existing_shareholder_agreements]']</value>
      <webElementGuid>aed230e7-9dae-40d9-bf02-58eeedf10281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[4]/div/div[5]/div/label/input</value>
      <webElementGuid>88f5d23e-9fa2-460c-ad2a-2fff25cf3647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[5]/div/label/input</value>
      <webElementGuid>35890ecc-82ec-4329-b742-68432a5ed75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'details[handover_info][articles_and_governance][existing_shareholder_agreements]']</value>
      <webElementGuid>3eed9740-b47d-4a64-b224-79566c92ee5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
