<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do they want to disable shareholder m_62066f</name>
   <tag></tag>
   <elementGuidId>3f6d73bd-0f96-4b81-a86c-1b0ad8e14831</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='details[handover_info][cap_table][disable_shareholder_management]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;details[handover_info][cap_table][disable_shareholder_management]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70b5fe76-5618-4b63-b59a-3e61768493ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7719b332-7acb-48d0-80ca-1622dca75e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-1</value>
      <webElementGuid>37e43246-cf1b-4a9b-b2ba-8d4863e62d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details[handover_info][cap_table][disable_shareholder_management]</value>
      <webElementGuid>3fd54b23-0f8b-441d-92a7-2e37fa52328c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>bc5f5cd1-2048-488c-8af2-ae03d0eb41d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[3]/div[@class=&quot;width-500&quot;]/div[@class=&quot;mb-3&quot;]/label[@class=&quot;radio-control-stacked&quot;]/input[@class=&quot;mr-1&quot;]</value>
      <webElementGuid>52603a77-cb3f-45b6-b144-0aa1f7e330c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='details[handover_info][cap_table][disable_shareholder_management]']</value>
      <webElementGuid>01b256d2-ef6f-4ade-b803-7f5f0ee26bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[3]/div/div[11]/label/input</value>
      <webElementGuid>7b4ee94a-a008-4989-965e-4efe8e26b5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/label/input</value>
      <webElementGuid>e4868779-a586-4bd6-a89b-9219b75e6634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'details[handover_info][cap_table][disable_shareholder_management]']</value>
      <webElementGuid>fdb702c1-0e98-405f-97db-512baebbbbb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
