<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Are they changing their Articles of A_3a6b40</name>
   <tag></tag>
   <elementGuidId>5778751d-d3bd-4125-9c31-20ca8837dd70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='details[handover_info][articles_and_governance][action]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;details[handover_info][articles_and_governance][action]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f957fd56-1dd8-429e-97e8-b7bd2010583c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8d33ea4f-e80b-4b7a-aeae-e80460f175b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-1</value>
      <webElementGuid>0d14bff8-63bd-4b8c-9117-9381bd8fa78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details[handover_info][articles_and_governance][action]</value>
      <webElementGuid>9d582432-145a-4908-8b06-7d74c54712c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>keep_current_articles</value>
      <webElementGuid>9ef0c77b-ec1e-4190-be09-854a42112e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[4]/div[@class=&quot;width-500&quot;]/div[@class=&quot;mb-3&quot;]/label[@class=&quot;radio-control-stacked&quot;]/input[@class=&quot;mr-1&quot;]</value>
      <webElementGuid>e149fe69-962f-42ef-8c6d-0e213a5de5fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='details[handover_info][articles_and_governance][action]']</value>
      <webElementGuid>e82d9046-075b-4889-8f85-2413e49cd683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[4]/div/div[2]/label/input</value>
      <webElementGuid>ffe0f9fe-e90c-449a-b215-07e61a3f8103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/label/input</value>
      <webElementGuid>2df86d9d-4316-4701-88a5-e58541b360a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'details[handover_info][articles_and_governance][action]']</value>
      <webElementGuid>f86e2579-fb83-4a39-881b-4b1d3b6fb3dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
