<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Are they planning on changing anythin_86a66f</name>
   <tag></tag>
   <elementGuidId>a8ebef8b-b122-44a0-9a4f-9c5c87ae3eb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='details[handover_info][cap_table][any_planned_changes_in_next_6_months]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;details[handover_info][cap_table][any_planned_changes_in_next_6_months]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfc15596-55cb-4a26-b9cf-8ae19644ecb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5ab4c3a4-7d0f-47f1-b7ff-1e5fe6c874bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-1</value>
      <webElementGuid>94de5ec3-351f-4a72-a1d5-633b3e2f7b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details[handover_info][cap_table][any_planned_changes_in_next_6_months]</value>
      <webElementGuid>445e4ae7-47a9-41f7-98b7-70febbd7c689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>e1ad33e1-dedb-49ff-909a-ee17aae71669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[3]/div[@class=&quot;width-500&quot;]/div[@class=&quot;mb-3&quot;]/label[@class=&quot;radio-control-stacked&quot;]/input[@class=&quot;mr-1&quot;]</value>
      <webElementGuid>fa08bf3c-51bf-42c8-b975-7712cd80327c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='details[handover_info][cap_table][any_planned_changes_in_next_6_months]']</value>
      <webElementGuid>2917e0a8-1711-49ad-a8c4-746f08982bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[3]/div/div[14]/label/input</value>
      <webElementGuid>8f8f4399-a6c9-43a3-ab9f-518fa88ee7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/label/input</value>
      <webElementGuid>9ca91b34-a540-4e5c-b131-2d10c206fbfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'details[handover_info][cap_table][any_planned_changes_in_next_6_months]']</value>
      <webElementGuid>bf61246a-71db-4962-b628-35d210d013a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
