<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Are they planning on changing anythin_3668cd</name>
   <tag></tag>
   <elementGuidId>6369b3eb-3e5e-4977-b5c3-c25826944721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/form/div/div[3]/div/label[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>98430468-30f2-44b9-b222-85498cce1629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are they planning on changing anything or expect any share movements in the next 6 months?</value>
      <webElementGuid>9dd6b977-27ae-4af3-85d4-965de0f400ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[3]/div[@class=&quot;width-500&quot;]/label[6]</value>
      <webElementGuid>5d85ce0d-ee54-458c-af31-f14b4c5cbb62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[3]/div/label[6]</value>
      <webElementGuid>54290d59-735e-4ef2-a6d8-c89814844d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Are they planning on changing anything or expect any share movements in the next 6 months?']/parent::*</value>
      <webElementGuid>a9d7fd11-e711-4976-8ebe-c05d5964c3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[6]</value>
      <webElementGuid>5fca6ed2-383b-4b4a-8b9d-3c3f49c1c811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Are they planning on changing anything or expect any share movements in the next 6 months?' or . = 'Are they planning on changing anything or expect any share movements in the next 6 months?')]</value>
      <webElementGuid>8772a5a0-a70d-44d8-bb9d-76364f1933d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
