<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Additional charges</name>
   <tag></tag>
   <elementGuidId>6cf9556f-a19a-4f1f-bde1-09c73f22bc91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/form/div/div[5]/div/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(5) > div.width-500 > label:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7b9b7b72-d897-4d4c-91ce-ee3c92f7b66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Additional charges</value>
      <webElementGuid>9bec9610-2495-4a96-95ff-c9f4a79d0c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[5]/div[@class=&quot;width-500&quot;]/label[2]</value>
      <webElementGuid>d88e1594-5758-47a4-8a1f-db733c019f1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[5]/div/label[2]</value>
      <webElementGuid>6baa8231-e64d-4be7-92c1-e20fece0512a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Additional charges']/parent::*</value>
      <webElementGuid>077bbf1e-2658-415f-b75e-e983d3c88e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label[2]</value>
      <webElementGuid>1420af30-5dbf-4c24-b9f7-add985e4033c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Additional charges' or . = 'Additional charges')]</value>
      <webElementGuid>47198ece-fb95-42ad-9a3b-c3dd6bb0d520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
