<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Reason for subscription type</name>
   <tag></tag>
   <elementGuidId>9597d767-3945-41c1-ae1f-92a0ddff1d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/form/div/div[5]/div/div[6]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f01a1d25-7b67-467c-9e98-60e71b9887ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>vc7gki6x51SGmNL6</value>
      <webElementGuid>bcf55dc1-a7a6-4272-8949-974f6ca3e598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reason for subscription type</value>
      <webElementGuid>774685c6-454e-497d-b7ac-08456b87c030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[5]/div[@class=&quot;width-500&quot;]/div[@class=&quot;form-group form-group--optional&quot;]/label[1]</value>
      <webElementGuid>2f867ba5-29ba-46c6-b609-acf16ed3ab3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[5]/div/div[6]/label</value>
      <webElementGuid>21c1f472-7d21-435c-8a63-86dc1878d674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reason for subscription type']/parent::*</value>
      <webElementGuid>d9b5b200-f57c-4aa5-88af-ff86847b59f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[6]/label</value>
      <webElementGuid>f1ff993b-03f2-487c-a5e9-06429a522a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Reason for subscription type' or . = 'Reason for subscription type')]</value>
      <webElementGuid>0dd2d095-c69d-421b-bc7f-e61d7ff2271c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
