<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Number and type of agreements</name>
   <tag></tag>
   <elementGuidId>2492bda9-a1d5-4212-a547-402dab34ca5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/form/div/div[2]/div/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form > div > div:nth-of-type(2) > div.width-500 > div.form-group > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>02cff320-4732-46da-b3a0-ba059870f4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>MaW1pu8qbIEn5Dc8</value>
      <webElementGuid>9fa41d15-87ad-434d-9256-559a3172ef04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Number and type of agreements</value>
      <webElementGuid>0031e1ce-4766-4a81-974a-d65e1267f340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[2]/div[@class=&quot;width-500&quot;]/div[@class=&quot;form-group&quot;]/label[1]</value>
      <webElementGuid>bed4d3dd-edfa-4339-b9cb-12c4ecb57ba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[2]/div/div[3]/label</value>
      <webElementGuid>fa73ab48-0b1a-45e6-a7f6-ee14b94f8448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESU ready reckoner'])[1]/following::label[1]</value>
      <webElementGuid>8768ea7e-a090-44b3-9c0a-66275e6dc794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Number and type of agreements']/parent::*</value>
      <webElementGuid>b6b126b2-e48d-4a56-87ea-0127c0e808d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/label</value>
      <webElementGuid>be97dac1-5f45-4f0c-a962-934356050586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Number and type of agreements' or . = 'Number and type of agreements')]</value>
      <webElementGuid>4ca19bf7-0ff3-49cd-b750-13dd8dc99a22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
