<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Do they want to add any more Editors _91abcf</name>
   <tag></tag>
   <elementGuidId>b431fce0-fca4-48d3-bdb8-8d56bb65c4b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/form/div/div[6]/div[10]/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9b1bcd9b-a813-47b4-8486-f634d1ad4146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>VBUPtponX4j5sXGV</value>
      <webElementGuid>93cb587a-1161-4ed5-b7d9-a82aa620e644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Do they want to add any more Editors (Admin users), or read only Directors/Shareholders?</value>
      <webElementGuid>4e33314a-426e-46ea-bbc6-67cd0ba0c5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[6]/div[@class=&quot;width-500&quot;]/div[@class=&quot;form-group form-group--optional&quot;]/label[1]</value>
      <webElementGuid>ea96c0da-920f-4c51-b1a7-5b6ad27a8766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[6]/div[10]/div[2]/label</value>
      <webElementGuid>793a24ed-5d6d-4cd4-9c0b-99f8170543dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML document'])[1]/following::label[2]</value>
      <webElementGuid>2338c9a6-26eb-4c86-b37a-9c8ecb9417a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Do they want to add any more Editors (Admin users), or read only Directors/Shareholders?']/parent::*</value>
      <webElementGuid>e97f0bbd-d3f1-4f96-a3ff-46359a27b850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/label</value>
      <webElementGuid>6b881924-11ee-4588-a2a2-f720ddf47b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Do they want to add any more Editors (Admin users), or read only Directors/Shareholders?' or . = 'Do they want to add any more Editors (Admin users), or read only Directors/Shareholders?')]</value>
      <webElementGuid>0af063b8-1a9f-416f-9c43-f18692691792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
