<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Do they plan to use the platforms Co-_21e3ab</name>
   <tag></tag>
   <elementGuidId>42b4174c-2452-462a-b911-10812b616e23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/form/div/div[3]/div/label[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f881417d-56c7-45d5-8a4d-3f5c519cdb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Do they plan to use the platform’s Co-Sec functionality?</value>
      <webElementGuid>ae8d572f-31b9-4a21-b0e9-b0c6bf0ef6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[3]/div[@class=&quot;width-500&quot;]/label[4]</value>
      <webElementGuid>e75db6e7-5bce-4992-b630-0d9feb9c99f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[3]/div/label[4]</value>
      <webElementGuid>d30e58a0-6904-473f-ad69-46fc1ac5f0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Do they plan to use the platform’s Co-Sec functionality?']/parent::*</value>
      <webElementGuid>25a78f42-19da-4398-94be-0ad79c600b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]</value>
      <webElementGuid>8451cbee-b40d-4163-b2c5-a6e4ac7038a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Do they plan to use the platform’s Co-Sec functionality?' or . = 'Do they plan to use the platform’s Co-Sec functionality?')]</value>
      <webElementGuid>d0ca1fc9-dfdc-47f2-adef-931b1f1d7b65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
