<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_This will determine whether the customer _6ea016</name>
   <tag></tag>
   <elementGuidId>74d0c500-d819-490c-995e-883a3bfe0ced</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/form/div/div[4]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.width-500 > p.form-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f91a302e-c582-4cbb-8e2b-3d117901d2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text</value>
      <webElementGuid>6b3de92b-a2d2-4c4c-934a-2d9875d7937c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This will determine whether the customer is prompted to adopt our growth share clauses. For any other article amendments select 'Keep current articles'.</value>
      <webElementGuid>5c546707-55e8-4565-9a2a-707dc577bbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[4]/div[@class=&quot;width-500&quot;]/p[@class=&quot;form-text&quot;]</value>
      <webElementGuid>579e8022-8cf0-43a0-b671-75e04673c8b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[4]/div/p</value>
      <webElementGuid>b5c44358-fc82-49a2-a0b9-e64afb5a0b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/p</value>
      <webElementGuid>1752b9b6-6f63-4e81-b658-f0fcab2190d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = concat(&quot;This will determine whether the customer is prompted to adopt our growth share clauses. For any other article amendments select &quot; , &quot;'&quot; , &quot;Keep current articles&quot; , &quot;'&quot; , &quot;.&quot;) or . = concat(&quot;This will determine whether the customer is prompted to adopt our growth share clauses. For any other article amendments select &quot; , &quot;'&quot; , &quot;Keep current articles&quot; , &quot;'&quot; , &quot;.&quot;))]</value>
      <webElementGuid>1262b7fc-ef84-4f3d-9dd9-a8aa8b87c35e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
