<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Can we digitise their existing scheme _b7af11</name>
   <tag></tag>
   <elementGuidId>a1519118-016a-4695-ac2c-235ef35c1a29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/form/div/div[2]/div/div[5]/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form > div > div:nth-of-type(2) > div.width-500 > div.form-group > p.form-text > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>378e1336-0ac8-43be-a46c-52f57b1d8277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Can we digitise their existing scheme? Do they have any deeds that they want to use going forward? Is the vesting schedule unusual (e.g. third Friday of the month)?</value>
      <webElementGuid>634cb565-24d3-4d27-aed5-8219de395bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[2]/div[@class=&quot;width-500&quot;]/div[@class=&quot;form-group&quot;]/p[@class=&quot;form-text&quot;]/span[1]</value>
      <webElementGuid>710eeb76-317d-4f98-b103-e814d730a9d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[2]/div/div[5]/p/span</value>
      <webElementGuid>07da37b5-2c6e-40c3-8273-aa3afe47aac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cap table'])[2]/preceding::span[2]</value>
      <webElementGuid>d298f3d0-2e63-4bde-b8c0-7b2dfe378394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Can we digitise their existing scheme? Do they have any deeds that they want to use going forward? Is the vesting schedule unusual (e.g. third Friday of the month)?']/parent::*</value>
      <webElementGuid>9fee8451-3697-473e-9d90-cada3ad5dafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/p/span</value>
      <webElementGuid>5e59bd18-2944-4f74-8df3-b426a49772be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Can we digitise their existing scheme? Do they have any deeds that they want to use going forward? Is the vesting schedule unusual (e.g. third Friday of the month)?' or . = 'Can we digitise their existing scheme? Do they have any deeds that they want to use going forward? Is the vesting schedule unusual (e.g. third Friday of the month)?')]</value>
      <webElementGuid>81cff1d6-8941-4834-908a-992617ee909e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
