<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Enter the correct names of those w_d6a8a6</name>
   <tag></tag>
   <elementGuidId>558775c7-61c9-4e19-9872-b3db29224070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ithPNmGhDKrMpH2p']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ithPNmGhDKrMpH2p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>eb6c5967-50e6-4fe2-aa36-b1f9797d830d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eebe1f1f-d624-4f6a-b60b-61488a8585aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ithPNmGhDKrMpH2p</value>
      <webElementGuid>04e01618-a6e9-4fef-a976-26bd8b9b9f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details[handover_info][cap_table][reason_for_not_matching_names]</value>
      <webElementGuid>61f03dd6-7140-4d73-a2fe-145c2069700d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ithPNmGhDKrMpH2p&quot;)</value>
      <webElementGuid>ace0be79-e8b1-4d7b-a474-7269bf5f664b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ithPNmGhDKrMpH2p']</value>
      <webElementGuid>62cfb9ea-61ae-4b60-a1d6-17893b61243b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[3]/div/div[6]/div/textarea</value>
      <webElementGuid>931304e3-cd10-43c1-9246-44a34ab5421d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/textarea</value>
      <webElementGuid>e1fc6848-b91b-4350-8f85-6a24f19b662c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ithPNmGhDKrMpH2p' and @name = 'details[handover_info][cap_table][reason_for_not_matching_names]']</value>
      <webElementGuid>8f7c4008-49db-41f5-8ad5-aafded02502e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
