<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_For example ESU, HCT, etc. Whos ta_64819d</name>
   <tag></tag>
   <elementGuidId>d38f59fd-c786-4609-aa48-06146517d2db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='cP47lLTUML37FsRK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cP47lLTUML37FsRK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>49ff1b09-9d43-4277-b75c-47851cd8f15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ad38ac56-af07-401e-92c4-8276801757ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cP47lLTUML37FsRK</value>
      <webElementGuid>7c3269cc-dc15-41b8-b15f-2cc1f931e232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details[handover_info][billing][notes]</value>
      <webElementGuid>2b78fad1-e2d5-47a9-9c02-b721ca45f1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cP47lLTUML37FsRK&quot;)</value>
      <webElementGuid>696b95fe-265e-4a98-863f-af7e912b7cc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='cP47lLTUML37FsRK']</value>
      <webElementGuid>a62a7a2e-c2ba-44b3-837e-c8b9a46d2979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[5]/div/div[4]/div/textarea</value>
      <webElementGuid>095ba85f-90a1-49f0-9019-1dcaba300406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[4]/div/textarea</value>
      <webElementGuid>0e4194fd-a1fc-43d4-9873-3f7769f7baee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'cP47lLTUML37FsRK' and @name = 'details[handover_info][billing][notes]']</value>
      <webElementGuid>d261dfd2-eb09-4c98-a926-e02419f2ebb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
