<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Notes_detailshandover_infoexisting_b8a6de</name>
   <tag></tag>
   <elementGuidId>a46cbb4a-179f-4630-b852-e6913d1fd7b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='hz1Ix23gF3hKj9fE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hz1Ix23gF3hKj9fE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b15db220-da7c-48cb-84eb-bda6d210daa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>765eec36-faf5-44d2-931d-30f70fcbf840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hz1Ix23gF3hKj9fE</value>
      <webElementGuid>b0eed998-ed78-4b78-acfa-a28a05477b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details[handover_info][existing_scheme_upload][notes]</value>
      <webElementGuid>2cb9541c-6b96-46ae-a0d8-c2930d92d781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hz1Ix23gF3hKj9fE&quot;)</value>
      <webElementGuid>9598705d-54ed-4777-aef6-681d6484bca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='hz1Ix23gF3hKj9fE']</value>
      <webElementGuid>cd95e51a-f466-429c-8d92-e8f8a8d06a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>c68e8b7a-96d6-4e87-bd6d-00fd35e76a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>a3ef6efc-00f7-425b-9ac3-98b858a9deef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'hz1Ix23gF3hKj9fE' and @name = 'details[handover_info][existing_scheme_upload][notes]']</value>
      <webElementGuid>3c56ac5b-ee00-4843-b9c8-5f8ef771d86e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
