<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Reason_detailshandover_infocap_tab_0ee329</name>
   <tag></tag>
   <elementGuidId>9ca8d2f6-4a8b-4cb7-8b0e-016a7bd986ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ooUVy6v7YE5bFn1h']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ooUVy6v7YE5bFn1h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>326957f4-362d-4031-930f-d10437fbeb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>76578b8b-52e0-4631-b647-a3fd3eb46be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ooUVy6v7YE5bFn1h</value>
      <webElementGuid>193ed650-cfca-4d74-b3a7-a02869c074b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details[handover_info][cap_table][reason_for_disabling_shareholder_management]</value>
      <webElementGuid>ccdc6a27-829b-4db1-8bd2-d002e6a77c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ooUVy6v7YE5bFn1h&quot;)</value>
      <webElementGuid>5aa9b606-fa03-40d2-9b2c-3bd243bdb5de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ooUVy6v7YE5bFn1h']</value>
      <webElementGuid>0a2fbd3c-83e9-40d7-8a1b-6d7eb3fb224d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[3]/div/div[12]/div/textarea</value>
      <webElementGuid>3a0f21c5-027f-4883-8765-25bcf52e49c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/textarea</value>
      <webElementGuid>4f2da0f7-04a2-4bde-b7df-e0eb3fb09f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ooUVy6v7YE5bFn1h' and @name = 'details[handover_info][cap_table][reason_for_disabling_shareholder_management]']</value>
      <webElementGuid>4c126e70-ff72-4816-b222-8010fdab8862</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
