<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SE</name>
   <tag></tag>
   <elementGuidId>ff42f3bc-6439-4f71-8e84-d1a4583fa5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-nav-user']/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.d-flex.has-chevron</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '#user-account-menu' and @role = 'button' and @aria-label = 'Toggle user account menu' and (contains(text(), 'SE') or contains(., 'SE'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Toggle user account menu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c82d9c6-3e7f-4fe3-80f7-bf189805670a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#user-account-menu</value>
      <webElementGuid>084e6857-8bcb-4012-930e-365cec53dbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>804693c9-906e-4546-ae7a-91cccde4d48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Toggle user account menu</value>
      <webElementGuid>9963de04-4b39-4535-b8bf-f75e20e7b936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SE</value>
      <webElementGuid>ed376a3b-3ecf-4511-a6a3-522eb96e277c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-nav-user']/a[5]</value>
      <webElementGuid>2aec509c-55a7-4ccb-aa0d-ff62e322ffe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SP')]</value>
      <webElementGuid>77f9e613-3579-4e84-9fb2-4b15e63bd9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View &amp; send'])[4]/following::a[1]</value>
      <webElementGuid>c91801ac-bdd3-4364-b561-5390285d31c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self-Serve'])[1]/following::a[2]</value>
      <webElementGuid>7c0d0ed4-1566-4258-b279-908d8c34f40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal details &amp; password'])[1]/preceding::a[2]</value>
      <webElementGuid>3172854a-c1df-4f81-a4e6-94572ddf4f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy policy'])[1]/preceding::a[3]</value>
      <webElementGuid>4f3c4e4e-1925-426a-8db8-108cb0e7aff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SP']/parent::*</value>
      <webElementGuid>83753f4e-8caa-4f89-9dc4-5fd2b28f7bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#user-account-menu')]</value>
      <webElementGuid>48cc016f-e6f7-4d72-b403-aa2db1ac4807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>4353d522-1a3b-4e4b-810b-d1882e534687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#user-account-menu' and (text() = '
                SP
            ' or . = '
                SP
            ')]</value>
      <webElementGuid>1f1af92e-b7fa-4874-8747-49615656c49e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
