<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_upload-bulkST-Template</name>
   <tag></tag>
   <elementGuidId>a88a0ea4-ae60-4265-bf8a-e9269b4770f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'file_input' and @type = 'file']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#share_pool_size</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='share_pool_size']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='share_pool_size']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file_input</value>
      <webElementGuid>54c3fcf3-39d5-4421-bc3c-57f09e57ad6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>82537ac5-1402-42a9-8956-da077a83232d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='share_pool_size']</value>
      <webElementGuid>822b9681-8b7f-4685-aba8-f0b42e736308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='js-share-approval-form']/div[2]/input</value>
      <webElementGuid>80fa7efa-a48d-4a0b-959a-25cd1488281f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e05d1c29-ef1f-4795-b2c9-bc36bf0fe7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'share_pool_size' and @type = 'number' and @id = 'share_pool_size']</value>
      <webElementGuid>57414ec8-1133-4cad-9042-0f576b02c58c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
