<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of shares</name>
   <tag></tag>
   <elementGuidId>17d8b913-bd8d-4032-b738-6ba91485174c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='n8HK4GBtbRhhdQ9v']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @data-test-id = 'form-number-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#n8HK4GBtbRhhdQ9v</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='n8HK4GBtbRhhdQ9v']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29f857db-1ac7-45a1-89b6-8e61bd9c3ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd54160b-9ea5-4af3-9c49-d75e4dff2a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>feb9e531-52d2-42d3-82f6-0c2ae1f892d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7c54b619-5d83-4f7f-844d-05db02f306cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n8HK4GBtbRhhdQ9v</value>
      <webElementGuid>035da2f3-e30a-4062-9d9d-7103d0ed9325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0321c18f-fa7e-4473-9160-3f16ca43ba03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n8HK4GBtbRhhdQ9v&quot;)</value>
      <webElementGuid>b7b7e9f8-e2fc-4680-870e-b3f5d056e7ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='n8HK4GBtbRhhdQ9v']</value>
      <webElementGuid>c244ac77-d6f6-4965-810a-94213eff673d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div[2]/div[5]/div/input</value>
      <webElementGuid>e6b5029d-e64a-4369-8a34-84fe9bea56ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>b9a40c16-7695-47fe-9411-24b3a7a2d529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'n8HK4GBtbRhhdQ9v']</value>
      <webElementGuid>dba5b4dc-ef9a-4fc2-915c-0cc94dadcdcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
