<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tooltip-text_award-pre-tax-profit</name>
   <tag></tag>
   <elementGuidId>fe1fec38-df7e-4286-9210-c9798a1a0d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-popper__inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popper_mbwqiz5t_4ewo52']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;This amount shows the total value of your options after the exercise price is de&quot;i >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af3e0b4d-80ab-4d05-805d-c6a900fe1471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-popper__inner</value>
      <webElementGuid>46477e99-05e4-4490-ae35-c0552893ba21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This amount shows the total value of your options after the exercise price is deducted, but before taxes are applied</value>
      <webElementGuid>4e545462-f0b0-4e0b-a1dd-19107d43a5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popper_mbwqiz5t_4ewo52&quot;)/div[@class=&quot;v-popper__wrapper&quot;]/div[@class=&quot;v-popper__inner&quot;]</value>
      <webElementGuid>73275766-c5bb-46d3-af08-9c9b0af005c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popper_mbwqiz5t_4ewo52']/div[2]/div</value>
      <webElementGuid>e69880a2-a33f-45b2-a4ff-dcf4134eed85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave feedback'])[1]/following::div[4]</value>
      <webElementGuid>dc5f584f-81b9-4722-b406-212ac1609123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[1]/following::div[4]</value>
      <webElementGuid>2c94d3e6-ab05-4ccf-a1ed-9c7b1abfbad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>45bddc3d-71ed-4d78-983a-23dc1adf7ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'This amount shows the total value of your options after the exercise price is deducted, but before taxes are applied' or . = 'This amount shows the total value of your options after the exercise price is deducted, but before taxes are applied')]</value>
      <webElementGuid>f94829fd-a9b8-4ce0-a315-d61310e0e200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
