<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Shareholders</name>
   <tag></tag>
   <elementGuidId>ef76f751-9f84-4193-9b8f-c42cca06d3ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//h1[(contains(text(), 'Shareholders') or contains(., 'Shareholders'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[(text() = 'Share schemes')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='sidebarCollapse']/ul/li[3]/a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>18d3870c-908c-4cb2-835c-2ad24abc8e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shareholders</value>
      <webElementGuid>1b4670de-77ac-4f82-860f-709fb4f9d7ad</webElementGuid>
   </webElementProperties>
</WebElementEntity>
