<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_given_name</name>
   <tag></tag>
   <elementGuidId>95a37919-577d-4276-8229-2df211adfd80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BTXJQ5oYYcwCjpNn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BTXJQ5oYYcwCjpNn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24973236-c3fb-4dbb-b155-06595b78c917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>65ff51b8-af3a-455f-be90-6cfc71007aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0e592d4-0d4c-481a-ac40-6a7b268ce7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BTXJQ5oYYcwCjpNn</value>
      <webElementGuid>9e5cc906-0c0a-4c26-a687-92119d766a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>given_name</value>
      <webElementGuid>97e24d7a-4e07-4c14-b6c5-df3327b4399e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BTXJQ5oYYcwCjpNn&quot;)</value>
      <webElementGuid>7c3ca268-b4f5-4776-803b-c50543d99bc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BTXJQ5oYYcwCjpNn']</value>
      <webElementGuid>d29a1435-b57b-43fd-a8fc-37af6dc5ced4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='register-form']/div/div/input</value>
      <webElementGuid>02e95291-50d4-4f02-802c-99fdb687a22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d4841a16-7845-4a42-bb6e-d67192f00839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'BTXJQ5oYYcwCjpNn' and @name = 'given_name']</value>
      <webElementGuid>c34e03b3-b54f-4020-a5a2-435fe40ac703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
