<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dUi7WcQlvuLdEEw0</name>
   <tag></tag>
   <elementGuidId>a943bb94-2cd7-4b4d-a6d0-e8a2ad4aba09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dUi7WcQlvuLdEEw0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dUi7WcQlvuLdEEw0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;£ /share 1,000 shares at £0.0001 nominal value Save Cancel&quot;i] >> [data-test-id=&quot;form-number-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99c0b43f-aa4d-42d2-b3d9-3d1fd4c4bec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3e4d540-f4d7-4452-9dc1-45600e15cccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>4a611085-a90c-44a1-bd82-67a7f2d5a9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>52b11f6a-cdc5-4a70-a952-23160d11b39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dUi7WcQlvuLdEEw0</value>
      <webElementGuid>e8bd1779-459e-462b-93d4-1601ebaca194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0cc6390d-249d-43e6-8f5b-53c49f45f0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dUi7WcQlvuLdEEw0&quot;)</value>
      <webElementGuid>0beec08e-464a-4993-a362-a997737a1a07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dUi7WcQlvuLdEEw0']</value>
      <webElementGuid>2e9b4adb-a2a4-4243-b5d1-d74f38da60ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div[4]/div/div[2]/div/div[4]/div[2]/div/div/table/tbody/tr/td/div/div/div/div/input</value>
      <webElementGuid>faa9cf2e-ef76-4943-be46-7fecb2f38c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/input</value>
      <webElementGuid>57dcc68f-dc6b-4506-96cd-647a82c84a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dUi7WcQlvuLdEEw0']</value>
      <webElementGuid>773ca065-b6ec-4f9f-9e0f-8de4c6928aa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
