<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_share-class</name>
   <tag></tag>
   <elementGuidId>15ba1688-053c-455b-bdcd-1d4ca22f0fc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type = 'text' and @class = 'multiselect-search'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#L95fPejezWwDnpOu</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @class = 'multiselect-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='L95fPejezWwDnpOu']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a62d1880-3f6d-4670-93cb-05e12d600382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54e49cbe-20e5-4e5d-acce-7d6c5e9ff3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-search</value>
      <webElementGuid>db113306-0556-46e0-9827-47b979fd028e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>e9460c51-0701-4797-a848-3cfda8ee2102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>cec6fc91-dcbf-4277-83ae-173f2bcac2c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
