<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_simulate-with-option-option-pools-new-share-issuance</name>
   <tag></tag>
   <elementGuidId>795ddc8e-5d58-46a4-8aa2-37c1e3c7d63b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='L95fPejezWwDnpOu-multiselect-option-692094']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#L95fPejezWwDnpOu-multiselect-option-692094</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(contains(text(), 'Simulate with options, option pools &amp; new share issuance') or contains(., 'Simulate with options, option pools &amp; new share issuance'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//li[@id='L95fPejezWwDnpOu-multiselect-option-692094']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b7c5efad-138c-400e-88ae-a99b717169d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-option is-pointed</value>
      <webElementGuid>7154ddb9-0cd4-4960-af20-c8bf4ce6b155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5708d11c-b49c-4663-9d13-41f20b6dee06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simulate with options, option pools &amp; new share issuance</value>
      <webElementGuid>84d47f43-92ac-45a2-83ec-55d9b1b5b000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='L95fPejezWwDnpOu-multiselect-option-692094']</value>
      <webElementGuid>b57fd5d7-3590-4197-9551-8da8208e411e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='L95fPejezWwDnpOu-multiselect-options']/li[2]</value>
      <webElementGuid>861d5add-1c15-4283-8716-34b73aa9d62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[5]/following::li[1]</value>
      <webElementGuid>1c85c1ec-481d-4f0b-a267-bf0480fa77a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[4]/following::li[2]</value>
      <webElementGuid>98c7cf85-27f3-4131-bc59-1ae1ac0165eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barry Saunders (3,980 shares)'])[1]/preceding::li[1]</value>
      <webElementGuid>ab82ec42-be89-4ffa-bf7b-ec35ee9bc7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/ul/li[2]</value>
      <webElementGuid>4e0d9936-c711-417a-9df5-87bc8c509ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'L95fPejezWwDnpOu-multiselect-option-692094' and (text() = 'AdminSuper SP (999,980 shares)' or . = 'AdminSuper SP (999,980 shares)')]</value>
      <webElementGuid>8c30c658-c2e1-4312-b820-48c127244258</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
