<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_year</name>
   <tag></tag>
   <elementGuidId>8a8abf86-6c8a-4be6-be00-5b747fbc4a00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr[1]//button[normalize-space()='Reverse']&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'transfer_date_year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-md.btn-primary.btn-not-submit.v-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//button[@type='submit']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f396bd5f-7ab5-4972-8f15-43fc7d7953f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transfer_date_year</value>
      <webElementGuid>e34e3401-b15d-4179-9cb9-18aae4afb868</webElementGuid>
   </webElementProperties>
</WebElementEntity>
