<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_generate-financial</name>
   <tag></tag>
   <elementGuidId>b86088c7-b1da-4395-afb1-8224de553641</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/table/tbody/tr[2]/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Generate' or . = 'Generate')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/table/tbody/tr[2]/td[3]/a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce68c404-b744-44ad-bc6a-cd0a270cb2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.app.vestd.com/company/50135/reports/financial-report</value>
      <webElementGuid>2c61cb93-e6b4-4f87-b552-b3ab1162c1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate</value>
      <webElementGuid>4a0caf1e-a934-4ae1-a3a4-c5afdfda7010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-hover&quot;]/tbody[1]/tr[2]/td[3]/a[1]</value>
      <webElementGuid>dfe33c46-7f18-4ab0-821c-bcd3ce506815</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div/table/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>f8c21880-f119-4e84-9467-17fd38cbfabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Generate')])[2]</value>
      <webElementGuid>dcc3bb5b-3226-4ad4-be0f-c8937fa8e76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial report'])[1]/following::a[1]</value>
      <webElementGuid>e38a77aa-5b4b-4280-90ef-b45b9f6afa5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate'])[1]/following::a[1]</value>
      <webElementGuid>e7ec41ec-bf89-4b73-a47b-1de67b80f45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cap table reporting'])[1]/preceding::a[1]</value>
      <webElementGuid>46c2e543-a082-452f-a23b-564939e2dc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate'])[3]/preceding::a[1]</value>
      <webElementGuid>bbf7c82b-8731-44f9-a01c-1a0d5862ffe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.app.vestd.com/company/50135/reports/financial-report')]</value>
      <webElementGuid>3c94a82c-a91c-4f57-90ad-b1b7da5c2600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/a</value>
      <webElementGuid>e7404c90-c01d-4902-9a6d-64a49ead9045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.app.vestd.com/company/50135/reports/financial-report' and (text() = 'Generate' or . = 'Generate')]</value>
      <webElementGuid>308cee24-6568-4137-9e90-63c2427170db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
