<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_generate-financial</name>
   <tag></tag>
   <elementGuidId>b86088c7-b1da-4395-afb1-8224de553641</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/table/tbody/tr[2]/td[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'https://demo.app.vestd.com/company/50934/reports/financial-report' and (text() = 'Generate' or . = 'Generate')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/table/tbody/tr[2]/td[3]/a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7af55b75-118f-4627-ba73-441d1745bd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.app.vestd.com/company/50934/reports/financial-report</value>
      <webElementGuid>5ea729bc-4dc8-4938-8adb-0a0b9c6dfbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate</value>
      <webElementGuid>ede13aeb-edad-494b-a714-54e91615e680</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div/table/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>0b319e8c-75fe-41d8-a8de-3345f73dc875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Generate')])[2]</value>
      <webElementGuid>63e03eae-2243-4bd5-82f0-68c09266bb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial report'])[1]/following::a[1]</value>
      <webElementGuid>75526b47-bea2-4d70-85f6-f71c480b82d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate'])[1]/following::a[1]</value>
      <webElementGuid>97831561-9076-4319-be8d-a14214209eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cap table reporting'])[1]/preceding::a[1]</value>
      <webElementGuid>2bac73ea-a1c8-46b8-913b-3425d09be3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate'])[3]/preceding::a[1]</value>
      <webElementGuid>2291effe-1efb-45f9-819f-c69536823db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.app.vestd.com/company/50135/reports/financial-report')]</value>
      <webElementGuid>914c0dee-3773-4e9a-8131-a1e6a6310b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/a</value>
      <webElementGuid>d23f5915-2dde-436f-864a-1bfe784bf9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.app.vestd.com/company/50135/reports/financial-report' and (text() = 'Generate' or . = 'Generate')]</value>
      <webElementGuid>7cc3fbd6-f6e1-4ee9-a12e-1fc6fe7fa4bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
