<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_estimated-profit</name>
   <tag></tag>
   <elementGuidId>f84378f8-75f7-4f3c-80f3-e9990e5e9475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @data-test-id = 'form-number-input' and @class = 'form-control']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type = 'text' and @data-test-id = 'form-number-input' and @class = 'form-control'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#whF9bBj1ErBHFiwB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='whF9bBj1ErBHFiwB']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce6f6b45-4155-482d-a6a7-3bae76f99de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa63fa95-a7bf-4777-a0a9-99b28b9259d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>750a2ad8-a758-4910-b026-8663feaefbec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>36951820-5fa2-4ba9-bba4-685a1194853c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>whF9bBj1ErBHFiwB</value>
      <webElementGuid>5a98af10-a7f1-4b06-9b6e-9465b6d3b062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>de06d2a5-72aa-4a21-ae41-d505db5313b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;whF9bBj1ErBHFiwB&quot;)</value>
      <webElementGuid>6bae7d50-c4b1-4ca0-bd7a-08ddfe866bae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
