<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_shareholder-From</name>
   <tag></tag>
   <elementGuidId>3209b1e9-cd56-42aa-98c4-376e779f3183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L95fPejezWwDnpOu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type = 'text' and @class = 'multiselect-search'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @class = 'multiselect-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='L95fPejezWwDnpOu']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08ab36b9-a04b-46f3-9582-419818523c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6548ae97-bd33-40fe-8191-cc13e4ae87a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-search</value>
      <webElementGuid>6fa400bc-ff65-49a4-b6ff-bc64cddc7694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>L95fPejezWwDnpOu</value>
      <webElementGuid>661091e2-eb49-4c6a-acd4-4626835074b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>L95fPejezWwDnpOu-multiselect-options</value>
      <webElementGuid>faaec4d2-1322-487f-b638-ee3bde500ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>Select a shareholder</value>
      <webElementGuid>fa20cabf-f0ec-48b6-b136-715383218a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bd3306f9-f7fa-412e-82a6-78a8e400f58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>85a8df62-ed8d-4f5e-bc56-b9a067765787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>0cb6cb51-d414-4602-8609-54e7e010fd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>L95fPejezWwDnpOu-assist</value>
      <webElementGuid>fe67e0ab-f367-4058-b0db-337414532560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L95fPejezWwDnpOu&quot;)</value>
      <webElementGuid>332df1c7-7e2a-41e0-831c-e1cd82f8ddea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>e25b81e9-5e3e-4dbf-ac6d-b48c739b0bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>92e7241d-ced4-4712-85b7-b46a46497d03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
