<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_share-class</name>
   <tag></tag>
   <elementGuidId>e1567520-eaf7-4116-9540-6c9102564365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#share_class_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='share_class_id']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'share_class_id' and @name = 'share_class_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Share class&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7a3fa025-b7c0-4140-b8f6-d127f7b14b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>29dccbe8-9dc2-412a-a165-de4c4e6e5d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>share_class_id</value>
      <webElementGuid>0a6a2d81-c986-4880-906b-8113fcb1cc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>share_class_id</value>
      <webElementGuid>0129fb0c-7a1f-4add-802f-79bf85ed27b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectOrdinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)</value>
      <webElementGuid>7d928e0c-81c0-4754-bd69-6c9b7cc953a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share_class_id&quot;)</value>
      <webElementGuid>1404981a-f1a4-4099-9e13-c78ab5b6916a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='share_class_id']</value>
      <webElementGuid>00bedb9b-079f-4f51-9b63-5df73d305cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div/select</value>
      <webElementGuid>7691f2ce-ba0d-4b58-a339-c788f87cdb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share class'])[1]/following::select[1]</value>
      <webElementGuid>d5585ab8-f780-481d-a4cb-2528a753af9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/following::select[1]</value>
      <webElementGuid>f06e421b-2537-4caa-83dc-9f9dbec07825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[1]/preceding::select[1]</value>
      <webElementGuid>9790de6e-2a7c-4f34-a8ff-41b731c8a873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>259bb849-f1c7-4749-bfc5-ba3078985829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'share_class_id' and @name = 'share_class_id' and (text() = 'Please selectOrdinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)' or . = 'Please selectOrdinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)')]</value>
      <webElementGuid>3567f967-9f20-4c4c-93dd-b2061bf05067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
