<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NoneIncorporationFFRound oneRound two</name>
   <tag></tag>
   <elementGuidId>d7a118fb-3dcb-4c0f-9694-8d85aa43e739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#investment_round_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='investment_round_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Investment round&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5f4fd277-0b7b-4337-a0ef-6ec90fc661e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-width-lg</value>
      <webElementGuid>f5f79016-29a7-40a4-af36-52b959acf5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>investment_round_id</value>
      <webElementGuid>c986b53d-26bd-47ff-9883-d958da9aa500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>investment_round_id</value>
      <webElementGuid>7357fb26-5cb7-4677-9956-98869c298c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NoneIncorporationF&amp;FRound oneRound two</value>
      <webElementGuid>31588edb-526e-4769-b6cf-84b226f67de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;investment_round_id&quot;)</value>
      <webElementGuid>ae0077b1-c652-4c51-b82f-ceeeccb42179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='investment_round_id']</value>
      <webElementGuid>db5eaca0-0977-44cc-9e58-730a155a1e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div[6]/select</value>
      <webElementGuid>84223542-cfbf-4550-bc0d-cf6e3cee624d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investment round'])[1]/following::select[1]</value>
      <webElementGuid>3baf7afd-ae0f-4684-8c7f-f521a6bbc495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read the government guidance on paying stamp duty for stock transfers.'])[1]/following::select[1]</value>
      <webElementGuid>61019355-4a9c-4af2-9c18-935c463e3b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='create one'])[1]/preceding::select[1]</value>
      <webElementGuid>39a82679-095c-4055-8fee-2f6076f73b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::select[1]</value>
      <webElementGuid>a2f4a192-00cd-4c15-a143-16f807f371e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/select</value>
      <webElementGuid>115bad84-1fec-4c50-a502-adf839795cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'investment_round_id' and @name = 'investment_round_id' and (text() = 'NoneIncorporationF&amp;FRound oneRound two' or . = 'NoneIncorporationF&amp;FRound oneRound two')]</value>
      <webElementGuid>4bbe3506-5973-4308-aead-345cc999b386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
