<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tile_my-shares-breakdown-section</name>
   <tag></tag>
   <elementGuidId>6b2e583b-18c9-45f3-89af-fac83a862645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body > div > div.card.v-card.bg-white.mb-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;My shares breakdown 1,240 Ordinary shares Average price per share: £0.20161View &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab0a7272-c154-471a-a9ed-84983375af38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card v-card bg-white mb-3</value>
      <webElementGuid>7d6a5b7a-4334-43c3-a640-e7b3ddb868c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>v-card-component</value>
      <webElementGuid>7b73121b-b184-4ffd-8d1a-36d409199452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My shares breakdown 1,240 Ordinary shares Average price per share: £0.20161View transactions15 Ordinary shares Average price per share: £0View transaction</value>
      <webElementGuid>f63b5fae-aec1-4b67-9499-3ee5ec748cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center mt-4&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card v-card bg-white mb-3 expanded&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;card-body&quot;]/div[1]/div[@class=&quot;card v-card bg-white mb-3&quot;]</value>
      <webElementGuid>e7ee3cf6-d454-47f1-ae21-19282d08c958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>044a5b19-0ae8-4f90-95af-3844eb6c2999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projected value'])[1]/following::div[7]</value>
      <webElementGuid>2ec15d71-2de3-4fce-8cfd-d4a12d0619b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current profit'])[1]/following::div[12]</value>
      <webElementGuid>e08ebf69-4cf0-4f02-ae2c-f5e144ebfe3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>19679348-0e1e-479d-8db7-05c0b0a4be6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'My shares breakdown 1,240 Ordinary shares Average price per share: £0.20161View transactions15 Ordinary shares Average price per share: £0View transaction' or . = 'My shares breakdown 1,240 Ordinary shares Average price per share: £0.20161View transactions15 Ordinary shares Average price per share: £0View transaction')]</value>
      <webElementGuid>b74bbffc-d10c-4adc-9838-69f057993090</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
