<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_top-up-SH-res-day</name>
   <tag></tag>
   <elementGuidId>97d10152-cc52-4420-845e-232b8896270e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='share_pool_size']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'shareholder_resolution_date_day']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#share_pool_size</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='share_pool_size']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c9b7678-b136-4462-b2d2-596e0d08ed7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shareholder_resolution_date_day</value>
      <webElementGuid>06927bd0-a799-43a0-9f7c-3b4873b6277c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='share_pool_size']</value>
      <webElementGuid>add7e1c6-e059-48bd-b0cf-b771988a0c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='js-share-approval-form']/div[2]/input</value>
      <webElementGuid>d76302cc-da3d-44d1-968c-08cca2bc0dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>458bc377-975d-4012-907e-a95c8146074f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'share_pool_size' and @type = 'number' and @id = 'share_pool_size']</value>
      <webElementGuid>9b79e0c5-c6c8-4749-9034-796c1a8c19b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
