<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_top-up-SH-res-year</name>
   <tag></tag>
   <elementGuidId>310fe65c-586b-4d26-9a4b-45f8eb6687fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='share_pool_size']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'shareholder_resolution_date_year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#share_pool_size</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='share_pool_size']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>793de9ae-a1f3-4724-8ebb-c8af82328920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shareholder_resolution_date_year</value>
      <webElementGuid>448d9cd8-2019-4723-b99c-d110300397e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='share_pool_size']</value>
      <webElementGuid>acb79177-7596-4035-a77b-645023ae96c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='js-share-approval-form']/div[2]/input</value>
      <webElementGuid>0a1146b4-e42d-4cca-b1e3-2d7f99d617a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>f3af06f6-ec33-4904-a98f-6a6ac52f4a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'share_pool_size' and @type = 'number' and @id = 'share_pool_size']</value>
      <webElementGuid>1d513448-3f0d-4b45-8197-7012460c671a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
