<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_top-up-DR-res-day</name>
   <tag></tag>
   <elementGuidId>932e7dfb-cf02-45de-b093-535142a6652c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='share_pool_size']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'director_resolution_date_day']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#share_pool_size</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='share_pool_size']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53dfd01c-61c6-44ca-95be-5061a9a44eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>director_resolution_date_day</value>
      <webElementGuid>ab997d01-62b0-40f5-b768-0c6fcb19d0d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='share_pool_size']</value>
      <webElementGuid>a5323df1-e2dd-4616-9906-a08ccb98183e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='js-share-approval-form']/div[2]/input</value>
      <webElementGuid>e2b4a890-269b-4513-b627-bd9ac82acd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4dec278c-12a6-4b01-853b-fee5f0f4d32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'share_pool_size' and @type = 'number' and @id = 'share_pool_size']</value>
      <webElementGuid>daaa6fd0-4612-46a2-97e4-09f035785bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
