<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Ownership</name>
   <tag></tag>
   <elementGuidId>d0673d6d-971c-41a2-b178-aae58091a037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/h1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Ownership' or . = 'Ownership')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>13fc135a-18f1-4663-a74f-2f7faf7596a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ownership</value>
      <webElementGuid>1f59b7e8-a35c-46b7-9ad6-69edd64189a0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
