<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Option pool share class</name>
   <tag></tag>
   <elementGuidId>762f9c2e-8e95-4086-8d70-df1535afea84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='share_class_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#share_class_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Share class&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eb4729e1-4e82-45cf-b07f-50923704ce1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>05589ca4-1779-4b20-a681-c70925e4c874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>share_class_id</value>
      <webElementGuid>1025b9a3-6766-4f33-9279-9b9096f3fbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>share_class_id</value>
      <webElementGuid>cacf0aa0-cdbc-4eb4-a9bb-95f5e7e26717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select…Ordinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)</value>
      <webElementGuid>1061ce59-e1bc-4d05-bce0-93442312e02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share_class_id&quot;)</value>
      <webElementGuid>c550b609-dc47-4c63-b4d9-8775b637aec9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='share_class_id']</value>
      <webElementGuid>115b6a08-2f7f-4296-ba70-99dd73765250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='js-share-approval-form']/div[3]/select</value>
      <webElementGuid>0d6f7d4a-5d0f-49e6-931a-86a698d100d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share class'])[1]/following::select[1]</value>
      <webElementGuid>b3c1813a-6423-47fa-943d-5a763b91d572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pool size'])[1]/following::select[1]</value>
      <webElementGuid>00d8f906-828f-4135-b504-ef66a1ae876a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolutions'])[2]/preceding::select[1]</value>
      <webElementGuid>952ebf02-6ac2-495d-a7d3-62faffb35398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2ee39058-d21a-4b55-a306-6bc8a4440bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'share_class_id' and @name = 'share_class_id' and (text() = 'Please select…Ordinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)' or . = 'Please select…Ordinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)')]</value>
      <webElementGuid>cd818e4f-d76d-4d17-a193-712c3bdbb966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
