<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NI number</name>
   <tag></tag>
   <elementGuidId>e1196045-3f0c-49a6-9513-e52346194f46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='okhcUrIbmEUAwKVl']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'form-control' and @type = 'text' and @name = 'tax_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#okhcUrIbmEUAwKVl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='okhcUrIbmEUAwKVl']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07bdbe81-cb09-49de-aa20-2319d7823851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>73284b44-ae11-416f-ab99-7161246128a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>941f69f7-5cb4-4dce-b02c-c11f181d88a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tax_number</value>
      <webElementGuid>2d954430-24b3-4e31-9bd6-2e4bc844c1c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='okhcUrIbmEUAwKVl']</value>
      <webElementGuid>e19cc3b1-25c4-460b-9482-84e6326427b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[3]/form/div[3]/div/div/div[2]/div[6]/div/div/input</value>
      <webElementGuid>58469f57-2825-4925-bcaa-bcb130f65734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>9ab12c45-3ee6-4ed5-a22c-4957d2f5e290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'okhcUrIbmEUAwKVl' and @name = 'ni_number']</value>
      <webElementGuid>893eca20-0167-494d-a478-851dfc8c4845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
