<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_table-search</name>
   <tag></tag>
   <elementGuidId>b00d5c2c-13bf-4c0e-a5da-f617c5e54bf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text' and @name='table-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ZYFPoDxs8nrHgo5x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4546cbdf-f569-46c3-8ae2-838edfcb662d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9d868f27-0d19-46c4-ba47-8944623bd2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe18addd-d9fa-4b94-aa32-8a21594efb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ZYFPoDxs8nrHgo5x</value>
      <webElementGuid>81fc8d6c-1135-48f3-8429-7c27c04d34b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table-search</value>
      <webElementGuid>553bd0f6-d812-41ed-83a7-50b02616dd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ZYFPoDxs8nrHgo5x&quot;)</value>
      <webElementGuid>a7644daa-3e0c-451d-acef-391cbc491303</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ZYFPoDxs8nrHgo5x']</value>
      <webElementGuid>9742ca37-57fc-4e0d-a85b-1bc046d06528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vestd-table-search mr-0']/div/div/input</value>
      <webElementGuid>fe91c8cc-2179-4f30-96c3-4c6570f89778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>edac4f08-e73d-435a-8262-856090537770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ZYFPoDxs8nrHgo5x' and @name = 'table-search']</value>
      <webElementGuid>96db308c-2055-4be5-aced-8e6c7162e6bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
