<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_filter</name>
   <tag></tag>
   <elementGuidId>856f5c27-1523-4049-8739-de02562d00f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-12.pb-2 > div > div > div.col-12</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'btn btn-secondary mb-0 dropdown-toggle' and @id = 'dropdownMenuLink' and @role = 'button']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div[4]/div/div[2]/div/div/div[2]/div/div/div[4]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10592840-e86a-442a-887c-861e9f5d32ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary mb-0 dropdown-toggle</value>
      <webElementGuid>5fb18391-358f-4407-a9f1-4768e2b67f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuLink</value>
      <webElementGuid>2e6616e9-9ac5-47b8-afe4-f3b1e3806bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>41412d88-59ae-4030-9f6d-d3c3632f0a79</webElementGuid>
   </webElementProperties>
</WebElementEntity>
