<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cash consideration (total for all sha_20407e</name>
   <tag></tag>
   <elementGuidId>1f095e4a-c500-4dc8-9c9c-03e963759d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#consideration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='consideration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cash consideration (total for all shares being transferred)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f92d8009-cb9c-42d9-82fb-dae419c43406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-width-md</value>
      <webElementGuid>15beacfb-7260-4e33-a763-94a841c21419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>adedc3b7-9cc3-4d47-8347-dbb9f6bea1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ef06fe22-8be0-4df4-aa02-264042825025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>consideration</value>
      <webElementGuid>f15ed7d0-08fa-4988-a625-fb3eec120816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ca939982-f4c6-4400-ae2b-76cd0278ee56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>consideration</value>
      <webElementGuid>e4932e5c-f784-4008-9855-127d80a80c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consideration&quot;)</value>
      <webElementGuid>8e118816-30db-444c-9dd9-7c11d2f1ce61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='consideration']</value>
      <webElementGuid>664673ea-4a33-476e-ac5e-5c1c0e6ff98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div[3]/input</value>
      <webElementGuid>b07c3f75-6fbb-45c0-b9da-7babd2536558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>bf234abc-0a0c-472a-ad9c-7927bf21a512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'consideration' and @type = 'number' and @id = 'consideration']</value>
      <webElementGuid>4e32f1de-fd21-4223-b92d-7cbe9fc93157</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
