<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Chasity Feeney</name>
   <tag></tag>
   <elementGuidId>fd9eb08c-dc91-458e-a428-f5e18c5c35ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text' and @aria-placeholder='Select a shareholder']/following::div[2]/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MJgADa6s5wsDmDY8-multiselect-option-705872</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a508d611-4183-4a9a-96c4-6b1d0a8787b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-option is-pointed</value>
      <webElementGuid>1a77c801-95fb-49b6-a844-15334f6628f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MJgADa6s5wsDmDY8-multiselect-option-705872</value>
      <webElementGuid>37696b2b-f0e2-4bd4-9761-cb38e18f8d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>98d8f69e-2d17-4f03-a287-c7806e6a313a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Chasity Feeney</value>
      <webElementGuid>789af26b-c88a-425f-98ab-a8093c2852e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>04d3d8d3-b6f4-4e48-be8b-51a2bee717f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pointed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ef93332-0b54-46e9-81d5-a695452b1fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chasity Feeney</value>
      <webElementGuid>cac15da5-63fe-45cf-a703-34c3a33a161e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MJgADa6s5wsDmDY8-multiselect-option-705872&quot;)</value>
      <webElementGuid>060b0834-8cdf-4bd7-80a9-9bd2a1993f1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='MJgADa6s5wsDmDY8-multiselect-option-705872']</value>
      <webElementGuid>5fe556d3-c54f-414c-b18f-736362834204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='MJgADa6s5wsDmDY8-multiselect-options']/li[2]</value>
      <webElementGuid>26fb751c-2683-46f3-a6cb-5a7888196528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[5]/following::li[1]</value>
      <webElementGuid>e75f6c41-9e01-41e8-bdef-23f185301fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[4]/following::li[2]</value>
      <webElementGuid>bd058b86-4bb6-494b-bd9d-f5c90d6cc50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GSTest User'])[1]/preceding::li[1]</value>
      <webElementGuid>e529697a-c140-4a07-a906-2c6989b3c0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/ul/li[2]</value>
      <webElementGuid>cc6f304d-652c-4f27-98fc-77bcef03c239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'MJgADa6s5wsDmDY8-multiselect-option-705872' and (text() = 'Chasity Feeney' or . = 'Chasity Feeney')]</value>
      <webElementGuid>4e71a6ef-c8b0-4724-acf0-2d3397abf7fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
