<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_given_name</name>
   <tag></tag>
   <elementGuidId>f4d3ef1c-5aca-4c59-974f-b9a0c0624af3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#given_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='given_name']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;given_name&quot;)[count(. | //input[@class = 'form-control' and @name = 'given_name' and @type = 'text' and @id = 'given_name']) = count(//input[@class = 'form-control' and @name = 'given_name' and @type = 'text' and @id = 'given_name'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c57e2708-e82a-4fb3-8e70-572a7e51d12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d6a4bce4-e23d-46f1-ac90-fa137b0efcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>given_name</value>
      <webElementGuid>509e9be8-8779-4bbb-9ae8-d2303edc4a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95b0bd9d-7889-42df-8c6d-5eb7ceef96e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>given_name</value>
      <webElementGuid>0efc81a3-b016-46cb-b557-24931f9b839f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;given_name&quot;)</value>
      <webElementGuid>db84c36e-7c5d-4b3d-848e-52ee58aaf1e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='given_name']</value>
      <webElementGuid>a5fe48a4-b7c2-45cd-8720-253913c04af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-item-1']/div/div/div/input</value>
      <webElementGuid>0d29e1c5-f78e-4e6d-89e3-4fab242ec620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>2b73fedf-acf1-4283-b78a-3eec31242415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'given_name' and @type = 'text' and @id = 'given_name']</value>
      <webElementGuid>35e879d8-98fa-4387-a535-e41a8a9857de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
