<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Im done editing this investor</name>
   <tag></tag>
   <elementGuidId>3fb999f4-0bba-4f5e-8708-3c357bcf3b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-inline-block.flex-item.apply-changes > button.btn.btn-md.btn-primary.v-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;I'm done editing this investor&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45e2f72a-25a0-4d25-887d-503eec8068b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>56a98434-8189-41f3-8855-e2aa7e2774c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-md btn-primary v-btn</value>
      <webElementGuid>85526db2-417a-475d-be78-b28b23bbdff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>button-element</value>
      <webElementGuid>9d672722-ed17-4eca-8d29-96e821eddb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I'm done editing this investor</value>
      <webElementGuid>11c8058b-e8bd-4b8a-a470-df2ba3e5adcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card mb-3 investor&quot;]/div[@class=&quot;card-body bg-light p-3&quot;]/form[1]/fieldset[1]/div[@class=&quot;row mx-0 mb-0&quot;]/div[@class=&quot;flex-container w-100 justify-content-space-between&quot;]/div[@class=&quot;d-inline-block flex-item apply-changes&quot;]/button[@class=&quot;btn btn-md btn-primary v-btn&quot;]</value>
      <webElementGuid>aa7350ad-4904-4902-a94e-1f23c440248c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[7]</value>
      <webElementGuid>0fa5d0c2-82b5-4a29-9578-7ad2623c9f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div[3]/div/div[4]/div/form/fieldset/div[4]/div/div/button</value>
      <webElementGuid>9b277e5d-5b0c-4305-b678-2910f31dde77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You will need to select a share class before authorising shares.'])[1]/following::button[1]</value>
      <webElementGuid>ea6256e1-b378-477b-b5df-323cc7f83d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::button[1]</value>
      <webElementGuid>95964842-0000-4615-86be-e3e3a7abc417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More investment options'])[1]/preceding::button[1]</value>
      <webElementGuid>671821b2-58d7-45c9-8bff-a1db3c7a2bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>3e3edb7d-8564-4cf8-a276-9196e9c723f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = concat(&quot;I&quot; , &quot;'&quot; , &quot;m done editing this investor&quot;) or . = concat(&quot;I&quot; , &quot;'&quot; , &quot;m done editing this investor&quot;))]</value>
      <webElementGuid>3954498c-c5fb-4ec9-800a-1218bd16780e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
