<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Percent of round_x4p6ZBbWUva0WDZT</name>
   <tag></tag>
   <elementGuidId>89d71119-1f71-464b-9da9-b10940407896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#x4p6ZBbWUva0WDZT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='x4p6ZBbWUva0WDZT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Percent of round&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>115abd91-4b86-40ea-a080-642a8530e84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc462aff-0259-449f-a20c-c6cc1da36174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>c09db8b0-2c16-4eb9-a47a-438d67bb8a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>08484ca9-a1b0-4396-b575-e2ad8e9541cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>x4p6ZBbWUva0WDZT</value>
      <webElementGuid>29e1ca2e-5f22-461a-9811-7123c46bc8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>5514596c-c35b-4d32-bbaf-b80fd02cb7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;x4p6ZBbWUva0WDZT&quot;)</value>
      <webElementGuid>1af68962-3e71-4889-ba6e-1a8a2cf48a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='x4p6ZBbWUva0WDZT']</value>
      <webElementGuid>d61dd9c0-186a-4e34-a030-a41d4257da30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div[3]/div/div[4]/div/form/fieldset/div[2]/div[6]/div/div/input</value>
      <webElementGuid>5c48eca1-bf2f-43fb-8846-027b43202511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>cb18b0bd-c615-4a8e-8ef1-31504e74411a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'x4p6ZBbWUva0WDZT']</value>
      <webElementGuid>928284ef-81d2-4b01-bdcf-873a6c6c0713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
