<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__icI0PfMsjcHlTkzj</name>
   <tag></tag>
   <elementGuidId>41f5a8ee-b652-4629-9877-13459665ee26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icI0PfMsjcHlTkzj</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='icI0PfMsjcHlTkzj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Price per share&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>130aebef-9fe4-4c36-b583-3f76a4897818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2b51138-cd89-47d3-9a4a-a5f7bcea6699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>9e7b473c-3a64-495a-9f5d-8ad0b1e3bacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7bc2e996-b00b-4b23-8f6d-6978e312cdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icI0PfMsjcHlTkzj</value>
      <webElementGuid>03797ca7-a458-4db4-be03-5fa6668d06db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>81995dde-30d5-42bd-9102-62f15e496985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icI0PfMsjcHlTkzj&quot;)</value>
      <webElementGuid>453fe83b-a4d6-4e9a-adcf-ea633235eb0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='icI0PfMsjcHlTkzj']</value>
      <webElementGuid>63b05783-33f3-4d9f-a48f-78bae8d92567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div[3]/div/div[4]/div/form/fieldset/div[2]/div[3]/div/div/input</value>
      <webElementGuid>5bb207bf-183a-4862-b4ad-91be105390ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/input</value>
      <webElementGuid>9c3ff75b-7f1f-4a91-b619-cb4028ffeeff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'icI0PfMsjcHlTkzj']</value>
      <webElementGuid>98ea875d-0dbd-4ab2-a6f8-c5b1adfa5fdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
