<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Percent of company_piSHaxpFRVAgh7Nt</name>
   <tag></tag>
   <elementGuidId>9d7f8087-458f-484e-90c7-eca27e37819d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#piSHaxpFRVAgh7Nt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='piSHaxpFRVAgh7Nt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Percent of company&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ae3fe0f-3ee6-4096-9de9-ac46919901ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc35448f-d11c-4284-9bdf-a6ba9e4a7ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>fd7ee41a-02cc-47e0-86e5-50b3b5a5a0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8a2849bc-f22e-41a8-b4d9-bbb42e84ba2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>piSHaxpFRVAgh7Nt</value>
      <webElementGuid>cc12fbc9-dcbc-4eec-9cd9-e70cd345619d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4817d3d8-6f72-4d2c-b90f-fedb32709230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piSHaxpFRVAgh7Nt&quot;)</value>
      <webElementGuid>06e20343-b9cd-4a5e-b420-8be0e3a478e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='piSHaxpFRVAgh7Nt']</value>
      <webElementGuid>701118c6-10fd-49b6-9aa9-9416bf3e3682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div[3]/div/div[4]/div/form/fieldset/div[2]/div[5]/div/div/input</value>
      <webElementGuid>a66f6087-4c11-4de9-a9fe-c4c8ac1d968b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>c587ee12-6eba-453d-a6f1-c0a82d99fd86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'piSHaxpFRVAgh7Nt']</value>
      <webElementGuid>f521f6bb-589d-4a44-9096-cdff477b0f7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
