<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_For example ESU, HCT, etc. Whos takin_a27b4c</name>
   <tag></tag>
   <elementGuidId>25df7623-896a-4b94-be70-c9ac8a110850</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/form/div/div[5]/div/div[4]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a22b6a27-f0bb-4bc2-b19b-6b559a8ead1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cP47lLTUML37FsRK</value>
      <webElementGuid>370af2c8-20e8-4f0b-9cb8-c924aac785b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>For example ESU, HCT, etc. Who’s taking payment?</value>
      <webElementGuid>f4bf1e5e-38e2-47b3-85d1-90f2cf8fd248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/form[1]/div[1]/div[5]/div[@class=&quot;width-500&quot;]/div[@class=&quot;left-indent width-500&quot;]/div[@class=&quot;form-group&quot;]/label[1]</value>
      <webElementGuid>400fe538-b791-4936-be48-c07194c6d1d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div/div[5]/div/div[4]/div/label</value>
      <webElementGuid>f25f2924-3102-499c-a8d0-b806d117105b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='For example ESU, HCT, etc. Who’s taking payment?']/parent::*</value>
      <webElementGuid>51a361b3-dbc7-4e13-8d8f-2fa1ce648b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[4]/div/label</value>
      <webElementGuid>e4d065e2-cc80-49b0-a400-942400dca2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'For example ESU, HCT, etc. Who’s taking payment?' or . = 'For example ESU, HCT, etc. Who’s taking payment?')]</value>
      <webElementGuid>b520ae43-4ec4-463e-a03c-11b5a4e8d0d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
