<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter the number of shares_num_shares_5115e3</name>
   <tag></tag>
   <elementGuidId>2c551a98-b10f-4399-88ef-4d702545b010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text' and @name='num_shares_requested']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GcVf6BZF2IGTZm8K</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ee4f8b4-55b0-428d-8e97-4a352703e103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0626f8b9-39f1-4abd-a14d-6d05f2c5d8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3c84dbf-6a28-4dc2-baae-916c817f7278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GcVf6BZF2IGTZm8K</value>
      <webElementGuid>5cc93786-edc8-4a79-a5ec-567fc79976dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>num_shares_requested</value>
      <webElementGuid>29a583e5-354d-42af-ab25-3a46d342b65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GcVf6BZF2IGTZm8K&quot;)</value>
      <webElementGuid>49f07812-21e3-4ec6-9a76-36d6b7ec6cdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GcVf6BZF2IGTZm8K']</value>
      <webElementGuid>839dae39-0a93-469f-af10-1de4ee49ef96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/form/fieldset/div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>a68e2ecb-1d36-401f-b181-e41d94ade8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/input</value>
      <webElementGuid>3a90b94b-b63c-4460-8a38-b04b93355d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GcVf6BZF2IGTZm8K' and @name = 'num_shares_requested']</value>
      <webElementGuid>a9abd083-19bd-4fee-aaa1-347045113a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
