<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Help Centre_1</name>
   <tag></tag>
   <elementGuidId>5431dcdd-0c88-4aac-ae2c-39500f8aba48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebarCollapse']/ul[2]/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.navbar-nav.mb-md-4 > li.nav-item > a.nav-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Help Centre&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cbac8dad-bf33-46e9-a55e-6c1a53c2efe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9e36a956-f727-4861-94a0-5a02882ed0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.vestd.com/help?_gl=1*q3qbfk*_ga*MzI4NzQ5OTg3LjE3NDM1MDQwMTU.*_ga_52CVMT2H7J*MTc0MzUwNDAxNS4xLjEuMTc0MzUwNDA3OS42MC4wLjA.</value>
      <webElementGuid>db114483-c45b-475e-ab0f-8a3cdbcfe640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>9157c1f0-a983-4d6d-b5e4-f4d07fcc90cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Help Centre
                </value>
      <webElementGuid>f19016ea-b5b7-416c-80a7-7b4f2180ee3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarCollapse&quot;)/ul[@class=&quot;navbar-nav mb-md-4&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>b7ea5554-1624-4816-ae8c-8d2a2721b14f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarCollapse']/ul[2]/li/a</value>
      <webElementGuid>3ac13487-5107-4edb-954f-867bedadf036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Help Centre')]</value>
      <webElementGuid>956487d3-c26a-4d40-86b9-fb3340fa2db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company settings'])[1]/preceding::a[1]</value>
      <webElementGuid>ae771c60-262f-4284-929a-1ee060d37a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App - staff'])[1]/preceding::a[2]</value>
      <webElementGuid>d608a0e5-a8da-4d8b-80e0-1c089fd8b9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Help Centre']/parent::*</value>
      <webElementGuid>de576eb1-089a-43b7-bb6c-aa7ee13b8159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.vestd.com/help?_gl=1*q3qbfk*_ga*MzI4NzQ5OTg3LjE3NDM1MDQwMTU.*_ga_52CVMT2H7J*MTc0MzUwNDAxNS4xLjEuMTc0MzUwNDA3OS42MC4wLjA.')]</value>
      <webElementGuid>73f4ffbc-4876-41ad-97e9-1059456d910d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul[2]/li/a</value>
      <webElementGuid>ced050e6-0341-4232-bbcb-c4d34c091ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.vestd.com/help?_gl=1*q3qbfk*_ga*MzI4NzQ5OTg3LjE3NDM1MDQwMTU.*_ga_52CVMT2H7J*MTc0MzUwNDAxNS4xLjEuMTc0MzUwNDA3OS42MC4wLjA.' and (text() = ' Help Centre
                ' or . = ' Help Centre
                ')]</value>
      <webElementGuid>825e77ee-ee54-432d-ac34-e1ad2807c88a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
