<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_StatusCompleteCancelledExpiredNeeds signi_9a2bb1</name>
   <tag></tag>
   <elementGuidId>deea2733-4282-43e4-8eb5-76ae37db894d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.dropdown-toggle.child-filters</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='multi-dropdown-menu']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Status&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7ff2fa1-87e3-45e8-b391-86ecbe34a454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>99c895ff-1d2d-4497-9135-874954cfc1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item dropdown-toggle child-filters</value>
      <webElementGuid>53c7faee-d28a-4cd0-a7cd-253faf72def8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>StatusCompleteCancelledExpiredNeeds signingOff-platformSent for filingSent for signingWill be filed</value>
      <webElementGuid>fe34e1ac-38a5-4302-8bee-47270ed6640b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multi-dropdown-menu&quot;)/a[@class=&quot;dropdown-item dropdown-toggle child-filters&quot;]</value>
      <webElementGuid>6fb206ff-b1c7-475e-b160-1775bf8de6bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='multi-dropdown-menu']/a</value>
      <webElementGuid>43d0d750-ebd9-4508-b7ad-2f79b0312d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add filter'])[1]/following::a[1]</value>
      <webElementGuid>02527ac9-b920-4159-a92a-77d42cfecddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>ad3f16d5-9182-430d-ac3c-6e6236ff8f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a</value>
      <webElementGuid>c76376de-ff32-499b-afad-706e8525f921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'StatusCompleteCancelledExpiredNeeds signingOff-platformSent for filingSent for signingWill be filed' or . = 'StatusCompleteCancelledExpiredNeeds signingOff-platformSent for filingSent for signingWill be filed')]</value>
      <webElementGuid>1f45f019-16fd-486e-99bf-f6fbd84d08f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
