<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NI number_ni_number</name>
   <tag></tag>
   <elementGuidId>86a341c5-2f15-4421-9add-bcfc96200f06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#okhcUrIbmEUAwKVl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='okhcUrIbmEUAwKVl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;NI number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40c2735d-961f-454c-901f-285d52ff67a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>771c48ba-2118-466f-8928-d63e850cb994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a2b319c-b119-48e5-a453-e26cd4a2f535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>okhcUrIbmEUAwKVl</value>
      <webElementGuid>fb87dcc3-148a-4413-b761-ccb01f571db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ni_number</value>
      <webElementGuid>ca46fa2f-6f6d-44ce-8a2a-a870c546c7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;okhcUrIbmEUAwKVl&quot;)</value>
      <webElementGuid>8cec60d7-4f62-4b88-82d7-efd97674e5f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='okhcUrIbmEUAwKVl']</value>
      <webElementGuid>94b7108c-d80f-47a5-9335-0a3296c8a020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[3]/form/div[3]/div/div/div[2]/div[6]/div/div/input</value>
      <webElementGuid>33a76472-daad-43de-8cf4-802b78f3fc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>3a0cd4b2-49e8-4957-b4e5-0edff3a9b5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'okhcUrIbmEUAwKVl' and @name = 'ni_number']</value>
      <webElementGuid>d66fa9a8-7764-4d23-98fd-f23722a91726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
