<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_given_name</name>
   <tag></tag>
   <elementGuidId>d8a48504-76ee-41c1-8133-d7b1c839568a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#given_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='given_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cab7efb-7505-4def-b562-4e8e98beb17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7439abb5-c644-40e9-8d10-564c3e9284f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>given_name</value>
      <webElementGuid>755bc79a-c524-4f47-9032-be2f6df05f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>given_name</value>
      <webElementGuid>fa45905f-d5fb-4753-8da2-c5d0441c904a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>524e2b64-a08c-46fc-a445-f978d052d395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;given_name&quot;)</value>
      <webElementGuid>127e19cb-0379-40a8-bda7-bf1f5e88fca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='given_name']</value>
      <webElementGuid>d83817ae-9e06-4096-8d20-0b8f391cfc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[3]/form/div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>40581f99-a8c3-4cc0-98f6-e2e8cbb09cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/input</value>
      <webElementGuid>d35dc46d-8eef-483b-9101-31174ceaf795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'given_name' and @name = 'given_name']</value>
      <webElementGuid>ed297575-b543-462e-850e-4ff88dfc5916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
