<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Option pool</name>
   <tag></tag>
   <elementGuidId>1a7d34d5-7c54-47e2-9471-6091d3daf379</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;share_approval_id&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@class = 'form-control' and @name = 'share_approval_id']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='share_approval_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0e222163-af3c-49f5-8926-06f3bb14cfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d87a562a-2d26-46ab-be32-5fe6565590f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>share_approval_id</value>
      <webElementGuid>18ed42d8-958e-4e5b-8975-939b2f175f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select oneOption pool 1 (202,000 Ordinary shares remaining. 18th Oct 2024)CSOP Option Pool (800 Ordinary shares remaining. 18th Oct 2024)</value>
      <webElementGuid>7ccc2688-4dc9-4ddc-9bb8-100790c20b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;alert bg-light border&quot;]/form[1]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-lg-3 col-md-5&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>56b7e1cb-8259-49a2-87a4-00796cb3e064</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='share_approval_id']</value>
      <webElementGuid>ca7972eb-d543-4711-892b-7279c20e7e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[3]/form/div/div/select</value>
      <webElementGuid>ba0b2be5-894e-49a8-9b48-e908d48e647e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Option pool'])[1]/following::select[1]</value>
      <webElementGuid>143d2978-f743-46e8-8cb7-11e04a2380ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a new recipient'])[1]/following::select[1]</value>
      <webElementGuid>2e61eda8-531e-491e-83bd-a412bfcb8b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vesting start'])[1]/preceding::select[1]</value>
      <webElementGuid>15a618df-a383-44c3-a844-7855950fc28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[1]/preceding::select[1]</value>
      <webElementGuid>0eb451d6-062f-4e61-a28f-0a5edcb24724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d7914206-ea3c-46b6-b7c0-89ae82cce682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'share_approval_id' and (text() = 'Please select oneOption pool 1 (202,000 Ordinary shares remaining. 18th Oct 2024)CSOP Option Pool (800 Ordinary shares remaining. 18th Oct 2024)' or . = 'Please select oneOption pool 1 (202,000 Ordinary shares remaining. 18th Oct 2024)CSOP Option Pool (800 Ordinary shares remaining. 18th Oct 2024)')]</value>
      <webElementGuid>1eddae78-2c83-441c-88bd-dc2c20366599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
