<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No show the value graph and the calculator</name>
   <tag></tag>
   <elementGuidId>8d493506-85b3-44d7-b94c-8e2dec7b9750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='feature_recipient_dashboard_hide_calculator_and_graph_no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#feature_recipient_dashboard_hide_calculator_and_graph_no</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;No, show the value graph and calculator to the recipients&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e881ef3-679d-4ce1-be85-d2f647ee7ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>feature_recipient_dashboard_hide_calculator_and_graph_no</value>
      <webElementGuid>15fa723f-a79a-4f3d-af0e-536b4d2f6653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>926e8aff-222f-467a-8482-bd82d909e475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>feature_recipient_dashboard_hide_calculator_and_graph</value>
      <webElementGuid>717b0d56-569b-4a11-baf3-981e21e05b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1ff145e6-5db9-4f08-8778-7c3ddf95725e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feature_recipient_dashboard_hide_calculator_and_graph_no&quot;)</value>
      <webElementGuid>0253c583-e734-4dfd-98a7-87fa2a803699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='feature_recipient_dashboard_hide_calculator_and_graph_no']</value>
      <webElementGuid>60b95657-1aeb-4231-868c-c84f7ed9dbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div[10]/div[2]/div[2]/input</value>
      <webElementGuid>246a63b1-4b81-43a2-8ab7-ebf21c5462d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[2]/input</value>
      <webElementGuid>2c638805-6d29-4408-bcce-46ed73dd907e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'feature_recipient_dashboard_hide_calculator_and_graph_no' and @name = 'feature_recipient_dashboard_hide_calculator_and_graph' and @type = 'radio']</value>
      <webElementGuid>a9beec65-a2ae-4504-988e-3f2723af0c4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
