<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Vesting over time</name>
   <tag></tag>
   <elementGuidId>ce553fa1-c6db-491c-908f-32e2bbeb27cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div/div/div/div/div/div[3]/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vesting-type-until-nowvalue</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'form-check-input' and @type = 'radio' and @name = 'vesting_typevalue' and @id = 'vesting-type-over-timevalue' and @value = 'over-time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Vested until now&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1bc440e-5cc3-4b66-9d2e-e6bf15063737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>86bb0b6e-e882-42eb-ba68-4873018ac930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>28de1e45-4011-4c89-888a-ea711b37d7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vesting_typevalue</value>
      <webElementGuid>b13ec415-925a-4736-a691-bcbff54a90f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vesting-type-over-timevalue</value>
      <webElementGuid>a797039f-e424-4da9-a080-d9d77197b6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>over-time</value>
      <webElementGuid>d6d05135-0bb3-404d-89a6-bcd82c5830ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vesting-type-until-nowvalue']</value>
      <webElementGuid>dcb9eaf1-f279-41c6-9c59-173b3e5748ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>de8a6279-33fa-4f1e-9bc5-522e5a28ffe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>27b53aeb-edc0-4ec8-a77c-8aabc8afe504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'vesting_typevalue' and @id = 'vesting-type-until-nowvalue']</value>
      <webElementGuid>05be38d0-7dee-4c0e-ad25-a45b1eb55a8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
