<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_saveAndSendForSigning</name>
   <tag></tag>
   <elementGuidId>20ef407c-6576-4db9-8dd0-b43e6cfcfc5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#share_pool_size</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@value, 'Save and send for signing')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='share_pool_size']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='share_pool_size']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b07e0b2d-f8d6-4f2e-810f-96db9453976b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save and send for signing</value>
      <webElementGuid>ddec9d96-ec32-4244-a133-b87263c17ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='share_pool_size']</value>
      <webElementGuid>d37fbae8-6a76-4f8b-9a3d-e9522390f643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='js-share-approval-form']/div[2]/input</value>
      <webElementGuid>db8f365f-a4aa-43be-af3a-d2bc64436e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>622befec-0c1c-4dba-ae20-dad00d529a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'share_pool_size' and @type = 'number' and @id = 'share_pool_size']</value>
      <webElementGuid>4ae27682-c211-4901-a5e9-66c912ed933b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
