<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentType</name>
   <tag></tag>
   <elementGuidId>4b2d1321-d75f-421e-bf2c-287a9d971364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[normalize-space()='Document type']/following::input[@class='multiselect-search'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@type, 'text') and @class = 'multiselect-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.text-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Log out&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e9e2ecb-ac84-456c-8eb9-6de9e79eaf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ece49cf3-bea7-4085-a27d-01051a0bf617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-search</value>
      <webElementGuid>f0f8323b-0013-4f03-be50-73c04b8e5171</webElementGuid>
   </webElementProperties>
</WebElementEntity>
