<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Compliance</name>
   <tag></tag>
   <elementGuidId>48cc1611-58eb-4521-9051-cc45b44c212c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[(text() = 'Compliance' or . = 'Compliance')])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Compliance' or . = 'Compliance')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='sidebarCollapse']/ul/li[6]/a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20108f1b-74f6-4242-9997-7ed774512f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compliance</value>
      <webElementGuid>2cac3d95-1e0f-4cc8-ba48-6d7ae60a4fc9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
