<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reports</name>
   <tag></tag>
   <elementGuidId>e30a21bb-fcd1-43bb-8600-1c65ac202c43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.active</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(contains(text(), 'Reports') or contains(., 'Reports'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='sidebarCollapse']/ul/li[2]/a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df14edfd-6f29-4f1b-910c-cb8ea47bdffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reports</value>
      <webElementGuid>a75f30f5-4cb4-4006-b4e9-c9bd69755c86</webElementGuid>
   </webElementProperties>
</WebElementEntity>
