<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year_starts_at_year</name>
   <tag></tag>
   <elementGuidId>cb6b3b06-fc36-43c2-b487-162bb51dce47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#starts-at-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='starts-at-year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Year&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5119454-23ef-4757-9ef2-5f8cb9ebfbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>starts-at-year</value>
      <webElementGuid>111f89f8-40f1-4551-a3bd-9a93824ba6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>71a08aa4-4d38-4f16-af27-d7bc82d97531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1900</value>
      <webElementGuid>3835256c-e57b-44bb-b0cb-feec9687392e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2100</value>
      <webElementGuid>f0e1d769-b32f-4e09-9b91-83496c79ee2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>starts_at_year</value>
      <webElementGuid>64966766-f72f-46f2-8896-a87538572047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0362cafd-b1a5-41a5-a1f9-0751f1e4dd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;starts-at-year&quot;)</value>
      <webElementGuid>32c60953-017d-4595-a849-8cb5110698b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='starts-at-year']</value>
      <webElementGuid>b854c7d7-e14b-4ef5-a2cb-6bec673939e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/form/div[4]/div/div[3]/input</value>
      <webElementGuid>b58f6ec3-2eb1-4f8f-a078-300374efa6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/input</value>
      <webElementGuid>03937a38-a640-4300-90aa-bd47fde4ba3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'starts-at-year' and @name = 'starts_at_year' and @type = 'number']</value>
      <webElementGuid>514b62e2-6fd7-4ef2-bf43-24c0f7fb09dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
