<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Day_starts_at_day</name>
   <tag></tag>
   <elementGuidId>b76f22ba-27d9-4efe-8c5d-84a5f842b82a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#starts-at-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='starts-at-day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Day&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c29b0b34-e64a-4eb7-bd4a-feec95f33094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>starts-at-day</value>
      <webElementGuid>21f51874-65ae-4b23-9ae5-ae646012984e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2dab2002-7871-4043-988d-4b492a05916e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>45981194-6ddd-4375-bafb-594f45f66a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>debdd795-eb34-4eb3-8430-f9e9f9727138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>starts_at_day</value>
      <webElementGuid>a614913b-7947-4e93-bddb-7f0583d251cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>86e8aa97-422e-4bc2-913c-5e9f5ee2790b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;starts-at-day&quot;)</value>
      <webElementGuid>1df6ef46-5b5f-4fe9-a242-ad13b0487ad4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='starts-at-day']</value>
      <webElementGuid>3cd26a3f-0089-428a-a650-3046494b8a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/form/div[4]/div/div/input</value>
      <webElementGuid>37a0dc6e-d095-4992-9f7a-d8de2820bbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>296c3e9b-cf3c-4d2e-b906-4f743f876430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'starts-at-day' and @name = 'starts_at_day' and @type = 'number']</value>
      <webElementGuid>b633c35c-7a3b-4a6c-9e6c-64739f92bd85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
