<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please selectInvestment roundAccount_d52d9d</name>
   <tag></tag>
   <elementGuidId>3b56eb06-860b-43aa-9864-90ebadf0b307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='valuation_source']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#valuation_source</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Source&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c683ccae-727f-4298-8aea-ae714c95ce0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3b58517a-d892-4714-ac2c-8ecb0129cb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>valuation_source</value>
      <webElementGuid>418d220b-aec0-4c43-a46d-138272adceb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>valuation_source</value>
      <webElementGuid>e340c872-46bb-4da1-984c-336b32093e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectInvestment roundAccountant valuationDebt roundSelf valuation by company</value>
      <webElementGuid>9426ede2-975a-4d6f-98b6-6c631b4ddd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;valuation_source&quot;)</value>
      <webElementGuid>71b43f1d-80a9-4bae-8ecc-35a846166b59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='valuation_source']</value>
      <webElementGuid>3c713471-7817-419c-a72d-f795a2a8dbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/form/div/select</value>
      <webElementGuid>d157d904-483d-457a-83cd-78b8e6030c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source'])[1]/following::select[1]</value>
      <webElementGuid>4b5e13bf-c590-41f7-848d-3833e7f4d73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record a new company valuation'])[1]/following::select[1]</value>
      <webElementGuid>e2e794d8-7b6f-489e-a29f-31529c894e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/preceding::select[1]</value>
      <webElementGuid>080a935f-49c5-4a7d-8bcf-57271955df16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whole company valuation'])[1]/preceding::select[2]</value>
      <webElementGuid>07fc71fb-1ab9-4b23-be95-37aa4266263a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>647b99d2-5c2d-4094-a507-13de89b44914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'valuation_source' and @name = 'valuation_source' and (text() = 'Please selectInvestment roundAccountant valuationDebt roundSelf valuation by company' or . = 'Please selectInvestment roundAccountant valuationDebt roundSelf valuation by company')]</value>
      <webElementGuid>0b621e2f-97c0-4628-9bc8-f9b36564447b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
