<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tooltip-txt_my-shares</name>
   <tag></tag>
   <elementGuidId>6bb0283d-feb7-4cf7-89a2-18a02553d773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popper_28k7lwwe_7e8s3a']/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-popper__inner > div > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;This total includes all shares issued to you, both conditional and unconditional&quot;i >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59d3c1fe-b7d1-4280-9f68-50ccfb5e3d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This total includes all shares issued to you, both conditional and unconditional. Note: Exercised options are counted as unconditional shares.</value>
      <webElementGuid>e1e8cc8a-89e7-4c5b-aa29-8167c3297c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popper_28k7lwwe_7e8s3a&quot;)/div[@class=&quot;v-popper__wrapper&quot;]/div[@class=&quot;v-popper__inner&quot;]/div[1]/div[1]</value>
      <webElementGuid>679d5986-3ab1-46bc-9512-834d736dfea2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popper_28k7lwwe_7e8s3a']/div[2]/div/div/div</value>
      <webElementGuid>ebe33954-2163-4fd9-80f9-e57ce2555f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave feedback'])[1]/following::div[6]</value>
      <webElementGuid>0a22e952-34b5-4e9f-8872-e146cb2477d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[1]/following::div[6]</value>
      <webElementGuid>adcdee00-4f61-4528-87bf-e513b93bc6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>bfced29e-5125-408c-b8e6-95aa82e1deae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'This total includes all shares issued to you, both conditional and unconditional. Note: Exercised options are counted as unconditional shares.' or . = 'This total includes all shares issued to you, both conditional and unconditional. Note: Exercised options are counted as unconditional shares.')]</value>
      <webElementGuid>6a3a5948-06c3-4d2a-bf14-08d74c861017</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
