<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tooltip-txt_my-options</name>
   <tag></tag>
   <elementGuidId>c9f50200-8fe0-4703-8b24-15e6c559334b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popper_xo7axf86_7e8s3b']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-popper__inner</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'This shows the total number of options you’re eligible to receive (depending on the terms of your option agreements)' or . = 'This shows the total number of options you’re eligible to receive (depending on the terms of your option agreements)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='popper_xo7axf86_7e8s3b']/div[2]/div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa4a4577-2d30-4cf4-998d-471d9e9ab3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-popper__inner</value>
      <webElementGuid>4b3af842-6130-400b-ac35-043314472b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This shows the total number of options you’re eligible to receive (depending on the terms of your option agreements)</value>
      <webElementGuid>1e32af82-a68b-4d4e-b593-c831f0526af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popper_xo7axf86_7e8s3b&quot;)/div[@class=&quot;v-popper__wrapper&quot;]/div[@class=&quot;v-popper__inner&quot;]</value>
      <webElementGuid>241d1e92-9950-427e-812b-c3816e4fcc27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popper_xo7axf86_7e8s3b']/div[2]/div</value>
      <webElementGuid>c81ffe3f-e235-47c5-93a6-51a0acf8e6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave feedback'])[1]/following::div[4]</value>
      <webElementGuid>f13b6a1f-c88c-4471-9974-581dc73d6239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[1]/following::div[4]</value>
      <webElementGuid>6552be7c-362b-4c0f-ab08-8e5fddffda49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>c1e40bec-a9a8-4ab2-bad9-7c59e3643df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'This shows the total number of options you’re eligible to receive (depending on the terms of your option agreements)' or . = 'This shows the total number of options you’re eligible to receive (depending on the terms of your option agreements)')]</value>
      <webElementGuid>6437aaf1-df2e-4da2-93c2-69dc0afcf2be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
