<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_App - staff</name>
   <tag></tag>
   <elementGuidId>837025e9-dbe4-48c8-aaa4-705f98c58a8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.navbar-nav.mb-md-4 > li.nav-item > a.nav-link.text-admin.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebarCollapse']/ul[2]/li[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'nav-link text-admin collapsed' and @href = '#sidebarAdmin' and @data-toggle = 'collapse' and @role = 'button' and @aria-controls = 'sidebarAdmin' and @aria-expanded = 'false' and (text() = ' App - staff
                    ' or . = ' App - staff
                    ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='sidebarCollapse']/ul[2]/li[3]/a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>68d2102a-63f6-4751-b3a9-cae88e8bf7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link text-admin collapsed</value>
      <webElementGuid>4d87c9aa-b3a5-47e3-a589-a69171341766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#sidebarAdmin</value>
      <webElementGuid>d012884a-eb5e-417b-acbb-381960ae13b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>595d123c-d697-4f54-a09d-5b245e44f363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f509864-f9ee-4fbf-ac52-bc11c94c5b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sidebarAdmin</value>
      <webElementGuid>40910c9b-6a10-4d97-9577-f3fb243887fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>36019f7e-7b37-4e70-bb99-867cfc8cb2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> App - staff
                    </value>
      <webElementGuid>e646f81f-4a12-466e-80a7-af44b70b18ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarCollapse&quot;)/ul[@class=&quot;navbar-nav mb-md-4&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link text-admin collapsed&quot;]</value>
      <webElementGuid>3b19fa8f-1db4-4638-a9d9-711a8e607a02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarCollapse']/ul[2]/li[3]/a</value>
      <webElementGuid>d4a89392-d709-44d8-8573-b3c0fbb036e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'App - staff')]</value>
      <webElementGuid>ec055657-7bb5-400b-952b-cddb72b2519e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company settings'])[1]/following::a[1]</value>
      <webElementGuid>ede87ac2-7084-48e1-8b91-c46bf766dc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Centre'])[1]/following::a[2]</value>
      <webElementGuid>25f8cb34-364f-49a0-ab76-3d5a7db8ad52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[4]/preceding::a[1]</value>
      <webElementGuid>2602713b-334f-4054-970b-61824ccc1660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[3]/preceding::a[2]</value>
      <webElementGuid>f139e590-47f7-45d7-b223-0268a11ac9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='App - staff']/parent::*</value>
      <webElementGuid>92fe6697-16f3-488f-90e5-fba842ba1300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#sidebarAdmin')]</value>
      <webElementGuid>77c11764-7e04-4494-96c4-560656f229fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul[2]/li[3]/a</value>
      <webElementGuid>47d17015-ae01-4a1f-bee3-0e7baf0d763d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#sidebarAdmin' and (text() = ' App - staff
                    ' or . = ' App - staff
                    ')]</value>
      <webElementGuid>f53dd188-00f4-41d7-afb9-51315b09bf89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
