<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ToPlease select.Please select.Chasity F_f5903e</name>
   <tag></tag>
   <elementGuidId>2a46c60b-3b29-44bc-831a-7132c285b5af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='stock-transfer-form']/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f75b5d70-52c5-4e07-a1d6-e678c92d9e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group--required form-group multi-select w-100</value>
      <webElementGuid>8e9a69e3-189e-4f03-ae22-35b96d6c1384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ToPlease select...Please select...Chasity FeeneyGSTest UserGrant HolmesHarry SaundersJack WardLeda-Destin Stoltenberg-ReingerLuke CooperMillie LeePete KennedyRachel HallTara MorganTyler Kingfirst lastkjh mnbvAllen Ltd - Missing residential addressJensen-Dangelo Gleichner-King - Missing residential addressJessy-Gerald Turcotte-O'Hara - Missing residential addressJosiane-Danielle Spencer-Anderson - Missing residential addressShemar-Zena Olson-O'Conner - Missing residential addressYessenia-Mya O'Connell-Daugherty - Missing residential addressZula-Mario Hegmann-Lang - Missing residential addressPlease select...The recipient will need an address on file for the transfer form. If they’re not on the list you can add a shareholder.</value>
      <webElementGuid>36063d58-ea1c-40d1-9483-946bc01f05f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stock-transfer-form&quot;)/div[@class=&quot;stock-transfer-form&quot;]/div[@class=&quot;form-group--required form-group multi-select w-100&quot;]</value>
      <webElementGuid>cbfce21e-1e11-493c-a6f1-23571cd0e236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div[2]/div[3]</value>
      <webElementGuid>527d5c4e-fd7c-4051-9dc5-1cdddedc6019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Josiane-Danielle Spencer-Anderson - Missing residential address'])[1]/following::div[3]</value>
      <webElementGuid>f229e4f7-6c07-40c0-b972-ac2f7e10a4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jensen-Dangelo Gleichner-King - Missing residential address'])[1]/following::div[3]</value>
      <webElementGuid>186522ef-72a9-4c9f-972c-3a52abc8e640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>c1cc08bd-1ef9-48cc-875a-3dccaab2a867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;ToPlease select...Please select...Chasity FeeneyGSTest UserGrant HolmesHarry SaundersJack WardLeda-Destin Stoltenberg-ReingerLuke CooperMillie LeePete KennedyRachel HallTara MorganTyler Kingfirst lastkjh mnbvAllen Ltd - Missing residential addressJensen-Dangelo Gleichner-King - Missing residential addressJessy-Gerald Turcotte-O&quot; , &quot;'&quot; , &quot;Hara - Missing residential addressJosiane-Danielle Spencer-Anderson - Missing residential addressShemar-Zena Olson-O&quot; , &quot;'&quot; , &quot;Conner - Missing residential addressYessenia-Mya O&quot; , &quot;'&quot; , &quot;Connell-Daugherty - Missing residential addressZula-Mario Hegmann-Lang - Missing residential addressPlease select...The recipient will need an address on file for the transfer form. If they’re not on the list you can add a shareholder.&quot;) or . = concat(&quot;ToPlease select...Please select...Chasity FeeneyGSTest UserGrant HolmesHarry SaundersJack WardLeda-Destin Stoltenberg-ReingerLuke CooperMillie LeePete KennedyRachel HallTara MorganTyler Kingfirst lastkjh mnbvAllen Ltd - Missing residential addressJensen-Dangelo Gleichner-King - Missing residential addressJessy-Gerald Turcotte-O&quot; , &quot;'&quot; , &quot;Hara - Missing residential addressJosiane-Danielle Spencer-Anderson - Missing residential addressShemar-Zena Olson-O&quot; , &quot;'&quot; , &quot;Conner - Missing residential addressYessenia-Mya O&quot; , &quot;'&quot; , &quot;Connell-Daugherty - Missing residential addressZula-Mario Hegmann-Lang - Missing residential addressPlease select...The recipient will need an address on file for the transfer form. If they’re not on the list you can add a shareholder.&quot;))]</value>
      <webElementGuid>99d50695-7c4a-43ea-baf8-1e8981d55795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
