<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NoneIncorporationFFRound oneRound two</name>
   <tag></tag>
   <elementGuidId>15f105d9-eee0-4c4b-9ff5-24a11f484219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='investment_round_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#investment_round_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a9eed487-41a7-47a7-92f9-03f6ed635e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-width-lg</value>
      <webElementGuid>c94d9579-abea-4435-b723-c568ae9b8643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>investment_round_id</value>
      <webElementGuid>0e089df3-0cab-4ffb-a410-ed19fffed8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>investment_round_id</value>
      <webElementGuid>cfe4a8f7-bd55-4288-bafb-e092169d4ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NoneIncorporationF&amp;FRound oneRound two</value>
      <webElementGuid>27aa1ed0-3b43-415d-93c3-aa1343fcfa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;investment_round_id&quot;)</value>
      <webElementGuid>64e96a2f-29a8-4383-89e9-83f65da1a6f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='investment_round_id']</value>
      <webElementGuid>1be390c9-ce7a-43a6-83b6-153e79402a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div[6]/select</value>
      <webElementGuid>86b6eff0-6832-47c3-849a-a08e0700c746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investment round'])[1]/following::select[1]</value>
      <webElementGuid>62ab18a6-efe1-4f8a-8da6-3faa4680b0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read the government guidance on paying stamp duty for stock transfers.'])[1]/following::select[1]</value>
      <webElementGuid>e96c6ae4-e0f1-4bde-869c-bf4cf87fdaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='create one'])[1]/preceding::select[1]</value>
      <webElementGuid>03a7b0a1-6340-4cbe-8f66-9d342a822226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::select[1]</value>
      <webElementGuid>67d59f1c-fa2f-4b12-b3b1-0dcf09325e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/select</value>
      <webElementGuid>f3d02711-babe-4197-96bc-b85ca2d2035c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'investment_round_id' and @name = 'investment_round_id' and (text() = 'NoneIncorporationF&amp;FRound oneRound two' or . = 'NoneIncorporationF&amp;FRound oneRound two')]</value>
      <webElementGuid>da633ace-82e9-4088-8841-dce88598ef62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
