<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please selectNoYes</name>
   <tag></tag>
   <elementGuidId>a3f84bea-e879-4680-b4b2-d88ef351f18c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='over_1000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#over_1000</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>149387f1-f3b1-491a-89f2-32a34e7d6f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-width-lg</value>
      <webElementGuid>f3d75f06-6eed-475b-a696-58b94163d5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>over_1000</value>
      <webElementGuid>95d1331e-6093-43f9-bd9f-9c6cc106cca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>over_1000</value>
      <webElementGuid>4e2186bc-043b-4c15-aff2-da2b8d9f98f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectNoYes</value>
      <webElementGuid>3198ee1a-ba0b-47b6-ba29-32285b7fb918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;over_1000&quot;)</value>
      <webElementGuid>78dee386-39a2-4e34-a6a9-a692bdf783be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='over_1000']</value>
      <webElementGuid>55ecebd6-2a33-4f75-b944-2e1f6ffc381f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div[4]/select</value>
      <webElementGuid>69f33bc2-9d53-48e8-8f2e-947d3f737e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this part of a number of related transfers for this buyer that exceed £1,000 in aggregate?'])[1]/following::select[1]</value>
      <webElementGuid>8ca24bef-27f5-4e0f-bd6e-60d7507c84c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash consideration (total for all shares being transferred)'])[1]/following::select[1]</value>
      <webElementGuid>219e9c94-d80a-42cd-baf5-af17593e2df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read the government guidance on paying stamp duty for stock transfers.'])[1]/preceding::select[1]</value>
      <webElementGuid>c631a59f-b7e2-4674-9a39-91e18aaef28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investment round'])[1]/preceding::select[1]</value>
      <webElementGuid>f0262e94-eb80-4839-8ee9-41d3dafa8485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>098b07f3-441c-4f30-8eb5-3b6181001b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'over_1000' and @name = 'over_1000' and (text() = 'Please selectNoYes' or . = 'Please selectNoYes')]</value>
      <webElementGuid>a89b84bc-fc5c-48d3-8638-38c73fb2ea51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
