<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Barry Saunders</name>
   <tag></tag>
   <elementGuidId>ed5e447f-5d4e-4970-826d-a3219d861a6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EBtRFQk1BSOhV6BM-multiselect-option-692109</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='EBtRFQk1BSOhV6BM-multiselect-option-692109']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Barry Saunders&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2dc5792d-079a-4fd4-896b-53bd7e856d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-option is-pointed</value>
      <webElementGuid>fe3ef8f3-190b-450b-9a99-e8e0ae2f26ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EBtRFQk1BSOhV6BM-multiselect-option-692109</value>
      <webElementGuid>7a947920-3e45-4de7-b066-4df5a6039dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58c720dc-26f1-41fc-a1d6-63b3fae4a071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Barry Saunders</value>
      <webElementGuid>0b3682bf-9352-47e1-ad51-117d78ce6337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4b9fc580-5160-4c15-bf7a-cb1b4a61dfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pointed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32658a47-1748-450c-8357-5ba839f4f5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Barry Saunders</value>
      <webElementGuid>2bcfe7b5-8470-45b5-acae-2881e4673a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EBtRFQk1BSOhV6BM-multiselect-option-692109&quot;)</value>
      <webElementGuid>039615b8-16b4-42a3-8f5d-becb38dfd4c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='EBtRFQk1BSOhV6BM-multiselect-option-692109']</value>
      <webElementGuid>6747eb37-72a8-4e12-a97d-fc8b191b4d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='EBtRFQk1BSOhV6BM-multiselect-options']/li[4]</value>
      <webElementGuid>2366573a-4f4a-4784-8625-067d7d29d074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AdminSuper SP'])[1]/following::li[1]</value>
      <webElementGuid>859383c7-06f2-43c4-9cb6-7b32d6ccb8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[6]/following::li[3]</value>
      <webElementGuid>b9269f69-be3c-40e4-bf1f-900ab2aefd50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brice-Sonny Mertz-Becker'])[1]/preceding::li[1]</value>
      <webElementGuid>44232649-7fa8-495f-8dce-d5b78ae35b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/ul/li[4]</value>
      <webElementGuid>5273e1fc-4f12-47af-b00b-c0c3ac00316c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'EBtRFQk1BSOhV6BM-multiselect-option-692109' and (text() = 'Barry Saunders' or . = 'Barry Saunders')]</value>
      <webElementGuid>37bd83ff-575f-4368-97cc-bd32cb91d772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
