<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_fullHistory</name>
   <tag></tag>
   <elementGuidId>dfe8ad1a-7d0f-4a88-af8e-dd60033ac1e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.border-bottom.pb-2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//h5[(contains(text(), ' Full history (1 event)') or contains(., ' Full history (1 event)'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Full schedule (49 tranches)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>434dfec8-49e0-4ece-9bca-3486215e3eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Full history (1 event)</value>
      <webElementGuid>09a36d89-e592-48cc-a44f-1d0896544105</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/h5</value>
      <webElementGuid>1d3db468-bb0f-4b99-83ff-ac988bd46d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your vesting schedule'])[1]/following::h5[1]</value>
      <webElementGuid>2da14aee-8ec5-4103-8d10-951b0a0226a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overall value'])[1]/following::h5[1]</value>
      <webElementGuid>ea077572-fc13-48fe-9b6a-1e0a11d2a5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vested'])[1]/preceding::h5[1]</value>
      <webElementGuid>b465ccb5-fdba-4881-be7d-55db69a13904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vesting period'])[1]/preceding::h5[1]</value>
      <webElementGuid>b99ad5d8-d3c7-42bf-b0ec-7a741e33360c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Full schedule (49 tranches)']/parent::*</value>
      <webElementGuid>74940267-82f6-4dab-b49c-6a01f167b7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>ccf27f06-69f6-4653-9d5d-98a3845971cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Full schedule (49 tranches)' or . = 'Full schedule (49 tranches)')]</value>
      <webElementGuid>8b83a5a7-0510-461b-a3f3-a9cdf6e38abd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
