<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Day_to_date_day</name>
   <tag></tag>
   <elementGuidId>21dfa188-290e-4f63-9c92-79f8c8af72f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'report_period_end_at_day' and @type = 'number']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='to-date-day']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#to-date-day</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='to-date-day']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d24eb76-0307-4f02-8edd-d7847eb872c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>report_period_end_at_day</value>
      <webElementGuid>f3dc7a7e-c69b-4e57-8ed0-95465db3c997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>416b1741-85e3-416f-a9ff-d77149c5a48c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='to-date-day']</value>
      <webElementGuid>695bad11-ab5e-49e9-bb46-19fb077b3b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/form/fieldset/div/div[2]/div/div/div/input</value>
      <webElementGuid>bf0c1149-aaec-4712-a7a5-9f29fa9d029a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>9506e67f-721a-42a4-ab23-52eaec0c4cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'to-date-day' and @name = 'to_date_day' and @type = 'number']</value>
      <webElementGuid>67d914b2-d4a2-4ec4-a9f2-6a3980104e8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
