<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year_to_date_year</name>
   <tag></tag>
   <elementGuidId>0f86fafc-1586-4442-8ed7-105f0be77df8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'report_period_end_at_year' and @type = 'number']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='to-date-year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#to-date-year</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='to-date-year']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b14a8f1e-f741-4130-bd0d-487ed33d27d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>report_period_end_at_year</value>
      <webElementGuid>b05d3e07-e14e-4c4a-9503-871a38ae51a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5339a860-4ee8-43f6-be21-94f54ce382d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='to-date-year']</value>
      <webElementGuid>e6ff7723-7bed-4fc7-af33-17225c6157f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/form/fieldset/div/div[2]/div/div/div[3]/input</value>
      <webElementGuid>b0619431-78d3-465d-9559-50806739d923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/input</value>
      <webElementGuid>8d9d96e3-13ad-41ee-b99d-c4ff35111128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'to-date-year' and @name = 'to_date_year' and @type = 'number']</value>
      <webElementGuid>3d8ddd6a-4979-4bdc-bc0c-96e7d8867169</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
