<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Notification</name>
   <tag></tag>
   <elementGuidId>69e0ea1d-73b7-4e89-8781-dacd4c98f571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;top-nav-user&quot;]/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'notification-bell-icon' and @role = 'button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.text-admin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//ul[@id='staff-menu']/li[2]/a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c575f85-cd59-4d75-95a2-dfb14b59ce53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notification-bell-icon</value>
      <webElementGuid>e3d55c35-93c9-4d60-8355-a1541281b22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4ff35fa0-181b-471f-95b1-3aa2df5aef53</webElementGuid>
   </webElementProperties>
</WebElementEntity>
