<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_summayBarChevron</name>
   <tag></tag>
   <elementGuidId>6ae99d78-ddad-4b99-8a8e-82164e9ec6fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@data-test-id = 'v-icon-component']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.vi.vi-sm.mt-auto.ml-lg-2.mt-lg-0.vi-chevron-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@data-test-id = 'header-actions'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div/div/div/div/div[2]/i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>13b73ff5-f64a-4c0b-9e00-a64ab802726f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon feather icon-chevrons-down icon-default icon-sm icon-fixed icon-bg-none</value>
      <webElementGuid>2b63cfdb-9bb9-437a-83e9-4632760a0af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>v-icon-component</value>
      <webElementGuid>29521839-fd3b-4d9f-9586-ef21d571770f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
