<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_summayBarChevron</name>
   <tag></tag>
   <elementGuidId>6ae99d78-ddad-4b99-8a8e-82164e9ec6fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@data-test-id = 'v-icon-component']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.vi.vi-sm.mt-auto.ml-lg-2.mt-lg-0.vi-chevron-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@data-test-id = 'v-icon-component'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div/div/div/div/div[2]/i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ed511a05-4e35-4369-aab6-7d77f1b27de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon feather icon-chevrons-down icon-default icon-sm icon-fixed icon-bg-none</value>
      <webElementGuid>4425b184-e7e7-4460-a31f-b510613ebb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>v-icon-component</value>
      <webElementGuid>4c3dd78b-50c3-4a31-b2ec-0ab2e6812d0a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
