<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_price-paid</name>
   <tag></tag>
   <elementGuidId>a57d2770-41a6-4c70-b234-f0d15d26757d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ZVGphHxntxz6jRc7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='/share']/preceding::input[@type='text'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @data-test-id = 'form-number-input' and @class = 'form-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='ZVGphHxntxz6jRc7']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccbf59e0-3c8e-4c84-acef-e3ce1b569788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0610031c-df86-497c-bd99-72b5a42f3862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>852440c8-422d-43d4-bff1-332d967fb458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dbca7a3c-b1ab-4b18-8cdb-44429450f444</webElementGuid>
   </webElementProperties>
</WebElementEntity>
