<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_0.0050</name>
   <tag></tag>
   <elementGuidId>08f6cdfe-6f68-4884-8cb0-2a7a6081a714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uYSvIiTQ9VRLZ2CL']/div/div/div[2]/div/div/ul/li[4]/strong</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//strong[(contains(text(), '0.0055%') or contains(., '0.0055%'))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='uYSvIiTQ9VRLZ2CL']/div/div/div[2]/div/div/ul/li[4]/strong</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>ae14c30b-610a-4ef3-b112-4628f365748e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.0055%</value>
      <webElementGuid>529d6024-b3bb-4744-9a55-5219a98b5ff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uYSvIiTQ9VRLZ2CL']/div/div/div[2]/div/div/ul/li[4]/strong</value>
      <webElementGuid>d325dc3a-3083-498c-a673-fa4874a7dfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shares with equity rights:'])[1]/following::strong[1]</value>
      <webElementGuid>4ea169c2-ecc5-4c9e-bd0e-651b41814fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price paid per share:'])[1]/preceding::strong[1]</value>
      <webElementGuid>fd2e5556-7d43-4781-af2f-7165ef98c0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£1.00'])[1]/preceding::strong[1]</value>
      <webElementGuid>790dc874-67a9-4e40-94d3-a799d6072183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0.0050%']/parent::*</value>
      <webElementGuid>33be2ea0-2f99-4f49-828b-449f0f97b2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/strong</value>
      <webElementGuid>4c623803-1dae-405c-bb86-01b7c7d2f425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '0.0050%' or . = '0.0050%')]</value>
      <webElementGuid>3bdaa690-99b3-47a6-b520-8356a3828488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
