<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Unknown investor Draft</name>
   <tag></tag>
   <elementGuidId>0de6e702-ef52-4126-ba4b-42708a564efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div[3]/div/div[4]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.box.pl-0.pr-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Unknown investor Draft&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9fa6d41f-ad7e-4668-81ad-24a6fb7867f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box pl-0 pr-1</value>
      <webElementGuid>f1f2184a-772b-4476-8296-62c0b8f43832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unknown investor Draft</value>
      <webElementGuid>8e45701f-e245-4944-8838-656deb6a6072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card mb-3 investor&quot;]/div[@class=&quot;card-body bg-light p-3&quot;]/div[@class=&quot;row summary&quot;]/div[@class=&quot;col-10 summary-details&quot;]/div[@class=&quot;container pl-0&quot;]/div[@class=&quot;box pl-0 pr-1&quot;]</value>
      <webElementGuid>d72aa3c4-cd7e-4e88-911b-e195afc503c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div[3]/div/div[4]/div/div/div/div/div</value>
      <webElementGuid>e6f6ea11-29f9-4bf6-87f4-67cfe80fe3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shares'])[1]/preceding::div[1]</value>
      <webElementGuid>c8d83934-7637-4997-96b8-921c5b4679b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div</value>
      <webElementGuid>88119304-73b0-46b0-8f2b-cd44f6856e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Unknown investor Draft' or . = 'Unknown investor Draft')]</value>
      <webElementGuid>f3ce3a78-c1cb-4065-ab57-eef0ef072840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
