<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of shares_yDXuNAOsE9uHDRgb</name>
   <tag></tag>
   <elementGuidId>b86619c2-d584-4ba1-8d4d-b215a1738819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yDXuNAOsE9uHDRgb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='yDXuNAOsE9uHDRgb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;form-number-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12110eef-da75-4291-8558-9f27bc55e2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14b6f57b-07da-40f4-b43b-8fe7409f6e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>f5aaf4fd-dc2a-4f3e-8423-cbff3f7622ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f8f8f078-53a1-45fd-9e80-1a1612a6d275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yDXuNAOsE9uHDRgb</value>
      <webElementGuid>e4378e3f-b059-48eb-9685-68cc8ae46eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d8489ff4-5b8f-4496-bc65-fc525c0bf4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDXuNAOsE9uHDRgb&quot;)</value>
      <webElementGuid>4d42ae0d-4162-4aa1-a26d-1bffba1f7474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yDXuNAOsE9uHDRgb']</value>
      <webElementGuid>baf3bfc5-bf4f-4ba2-8ff0-9ceb57596ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div[2]/div[5]/div/input</value>
      <webElementGuid>78e6e003-cf55-4394-a168-5d8fdc08eef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>2794ed73-315a-4007-ba22-0372447add1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'yDXuNAOsE9uHDRgb']</value>
      <webElementGuid>ec02905c-7511-43d2-a550-667662a4d8dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
