<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please selectDEFERRED (non-voting) (_52e6d0</name>
   <tag></tag>
   <elementGuidId>d2e33760-0d5c-42da-a590-d5a5aab7e99d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#share_class_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='share_class_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Share class&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>435a1183-cf97-4327-acfb-0651498a0823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e248beec-9f3c-41b9-b3c7-bd37801e4c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>share_class_id</value>
      <webElementGuid>bf685876-acc6-4b25-bd65-6d423963682a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>share_class_id</value>
      <webElementGuid>78ebb74c-62ee-4294-bae9-d8d3f4f843e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectDEFERRED (non-voting) (£0.0001)Ordinary (voting) (£0.0001)Ordinary (voting) (£0.0001)</value>
      <webElementGuid>6e3efd49-71bc-4026-a9ee-96bd1b38479a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share_class_id&quot;)</value>
      <webElementGuid>269b1be8-8710-4b99-8597-c60933c0759b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='share_class_id']</value>
      <webElementGuid>1f62b43d-b15c-4ee3-ac0f-54b771487166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div/select</value>
      <webElementGuid>898f39a1-df41-4df4-b515-efc3892e7139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share class'])[1]/following::select[1]</value>
      <webElementGuid>bc51f5b9-bea4-4ec6-bf21-c2ece19368b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/following::select[1]</value>
      <webElementGuid>30c5fcc3-ab07-44fb-99d1-139675492060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[1]/preceding::select[1]</value>
      <webElementGuid>8f1e7f42-2414-40b9-9627-700bd613206f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c7ce9a69-bdbc-439c-9aa7-eb5353634093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'share_class_id' and @name = 'share_class_id' and (text() = 'Please selectDEFERRED (non-voting) (£0.0001)Ordinary (voting) (£0.0001)Ordinary (voting) (£0.0001)' or . = 'Please selectDEFERRED (non-voting) (£0.0001)Ordinary (voting) (£0.0001)Ordinary (voting) (£0.0001)')]</value>
      <webElementGuid>93da81ea-77ec-4dcc-b5a6-5ca0161739ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
