<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_shareclass</name>
   <tag></tag>
   <elementGuidId>8d53f772-d0d3-4de2-a8c3-2e036f4126ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'share_class_id' and @name = 'share_class_id' and (text() = 'Please selectOrdinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)' or . = 'Please selectOrdinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#share_class_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='share_class_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Share class&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dc8a7df1-a213-4538-a3f5-4db99e1cd177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d9c902e0-54b5-4dbc-9aa5-bb663145b1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>share_class_id</value>
      <webElementGuid>4f001282-dba8-442f-9379-e0488b581c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>share_class_id</value>
      <webElementGuid>7a5ee6f7-d594-474e-ad1b-586ab77f10cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectOrdinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)</value>
      <webElementGuid>61f3032c-4d1e-4e78-b430-bdd36a5008ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share_class_id&quot;)</value>
      <webElementGuid>6a297819-c07e-4f4b-addc-258aa3657ed7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='share_class_id']</value>
      <webElementGuid>ee358d6e-b699-4568-b6ef-c7654a8f5223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stock-transfer-form']/div/select</value>
      <webElementGuid>060ebe24-1726-4f2a-bafc-04d0f04ccb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share class'])[1]/following::select[1]</value>
      <webElementGuid>3f1bac01-9ecd-4bef-91b1-c58069d613ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/following::select[1]</value>
      <webElementGuid>0fe68618-decd-480a-99d3-8c5562c08248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[1]/preceding::select[1]</value>
      <webElementGuid>c5337d5f-5279-4d0b-b1eb-48eae228cf70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>aac9105d-5391-4bfd-873c-9f1eb43f22ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'share_class_id' and @name = 'share_class_id' and (text() = 'Please selectOrdinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)' or . = 'Please selectOrdinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)')]</value>
      <webElementGuid>1f3a25f7-bba1-4954-898d-0d8ae17a7e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
