<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes, hide the value graph and the calculator</name>
   <tag></tag>
   <elementGuidId>8d493506-85b3-44d7-b94c-8e2dec7b9750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='feature_recipient_dashboard_hide_calculator_and_graph_no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#feature_recipient_dashboard_hide_calculator_and_graph_no</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;No, show the value graph and calculator to the recipients&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eeac5e64-29b7-4964-809e-82f03f3156bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>feature_recipient_dashboard_hide_calculator_and_graph_no</value>
      <webElementGuid>288bcfb0-8d1f-4cea-af6b-9404d992feea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>ac53d4f0-b445-4ada-8359-f904e827a34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>feature_recipient_dashboard_hide_calculator_and_graph</value>
      <webElementGuid>460f4a40-d748-4c8c-bb92-b13155b0202d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5e28b4b2-b86a-4b3f-962c-aa82c455c026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feature_recipient_dashboard_hide_calculator_and_graph_no&quot;)</value>
      <webElementGuid>0359e415-1dff-431e-8b34-2d05079183a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='feature_recipient_dashboard_hide_calculator_and_graph_no']</value>
      <webElementGuid>06f17446-11b2-4321-ad06-0996caa4e067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/div[10]/div[2]/div[2]/input</value>
      <webElementGuid>50a4e8d0-beeb-4a06-a72f-814c96cd56cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[2]/input</value>
      <webElementGuid>7eaf8baa-c6c3-487a-b0e4-e9a71f6294a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'feature_recipient_dashboard_hide_calculator_and_graph_no' and @name = 'feature_recipient_dashboard_hide_calculator_and_graph' and @type = 'radio']</value>
      <webElementGuid>b91920ea-46af-4bbd-a2b8-65e9062ee471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
