<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What will the exercise price be</name>
   <tag></tag>
   <elementGuidId>31d07d21-5f36-4bdd-b42c-f54f9f784a3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UhIIiGkOvR286gyp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UhIIiGkOvR286gyp']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @data-test-id = 'form-number-input' and @class = 'form-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='UhIIiGkOvR286gyp']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c8f7fda-905d-4583-92f3-34009c3a7aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eda82ef2-ed39-43b4-bcd1-13c9446202c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>f51cd4ed-0736-4eb7-8657-f40df4026f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a4b9ce8b-cf5b-45c3-825f-1302d4706bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UhIIiGkOvR286gyp</value>
      <webElementGuid>19dc47b6-06de-445b-a0bc-77a6ea876a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>39f73caf-2fc1-420b-95f0-bfc1a2e13e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UhIIiGkOvR286gyp&quot;)</value>
      <webElementGuid>1498c9ba-6fd3-40e2-b257-9e0d8d6183c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UhIIiGkOvR286gyp']</value>
      <webElementGuid>6469fda3-29b1-4261-84d4-4fc7b7d749c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9b503e8d-c4ff-4bd4-879f-6882df94d6e6']/div/input</value>
      <webElementGuid>a84dcd03-d283-482e-89e7-849364251e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>52d80368-c54d-4e2d-b916-f324df70ae4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'UhIIiGkOvR286gyp']</value>
      <webElementGuid>d526a8d5-b5dd-4b12-9fe1-c38faa323594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
