<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_As soon as the option is accepted Eac_0c9b85</name>
   <tag></tag>
   <elementGuidId>d5968d6d-fd5f-4389-a5f6-05b9bc12824b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='js-workflow-form']/fieldset/div/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;As soon as the option is accepted Each option will be granted on the day the rec&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a184e264-d7f4-4886-bfe5-f8f23d0f93b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-block mb-4 flex-grow-1 flex-shrink-1 choice-label</value>
      <webElementGuid>2b0538f4-8f35-4216-be68-87796716a6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>acceptance</value>
      <webElementGuid>9bf547d8-e040-4d0c-a8e1-2856400e14c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> As soon as the option is accepted Each option will be granted on the day the recipient accepts it.</value>
      <webElementGuid>1a84cbcd-ce4c-4d52-9b48-455dd2304e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-workflow-form&quot;)/fieldset[1]/div[@class=&quot;row mb-4 mt-5&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-4 col-lg-6 d-flex col-xl max-w-xl-choice&quot;]/label[@class=&quot;d-block mb-4 flex-grow-1 flex-shrink-1 choice-label&quot;]</value>
      <webElementGuid>02594e03-ee23-498d-b5c4-16219ec79cba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='js-workflow-form']/fieldset/div/div[2]/label</value>
      <webElementGuid>f568eb59-732e-4ff4-89a2-20ca08d4f890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specify the date all agreements will be granted.'])[1]/following::label[1]</value>
      <webElementGuid>e9fcc721-46d7-4673-ade8-ac6af3c307aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On a particular date'])[1]/following::label[1]</value>
      <webElementGuid>e2dab3b2-fe77-48f1-b766-d0dd4431d538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>3522c9e0-5ad2-4709-a748-f38490d61957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' As soon as the option is accepted Each option will be granted on the day the recipient accepts it.' or . = ' As soon as the option is accepted Each option will be granted on the day the recipient accepts it.')]</value>
      <webElementGuid>f22719ef-bfab-4614-b0c2-a43c4aeb0336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
