<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_user-account</name>
   <tag></tag>
   <elementGuidId>c15972d1-03c8-4d42-b80c-4264a1844ef3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.text-admin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;top-nav-user&quot;]/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'd-flex has-chevron']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//ul[@id='staff-menu']/li[2]/a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0fbf0aa-1ad7-4bd1-bb70-3d22537b9118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex has-chevron</value>
      <webElementGuid>3b6b7cdb-bb5a-4e5b-8a28-07bd194a6dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d1637e5-b845-412f-99ab-87250dbe2686</webElementGuid>
   </webElementProperties>
</WebElementEntity>
