<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_Director reappointment</name>
   <tag></tag>
   <elementGuidId>1a2f3b66-4a16-4a3b-94c9-562a60448a82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from-date-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from-date-day']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(contains(text(), 'Director reappointment started.') or contains(., 'Director reappointment started.')) and @class = 'alert-content d-block']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='from-date-day']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a84abdc-79ba-4030-ae1a-cd6925c9e67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Director reappointment started.</value>
      <webElementGuid>1340f97b-ed86-4c9c-8e7d-5ae6135d5724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert-content d-block</value>
      <webElementGuid>2e38f3f5-5053-4f08-a1af-0f38c0075548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from-date-day']</value>
      <webElementGuid>981dbc30-3b72-4980-98f9-670151014689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/form/fieldset/div/div/div/div/div/input</value>
      <webElementGuid>80e0818f-aa7b-4aa8-8811-31f74b758aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>f622b351-cbdb-4148-9671-6cc027f5ccdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'from-date-day' and @name = 'from_date_day' and @type = 'number']</value>
      <webElementGuid>0a7a6401-d1e9-4032-907a-6ec491d271d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
