<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_appointedYear</name>
   <tag></tag>
   <elementGuidId>ef427696-eabd-40df-a51c-f51280ba8b17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from-date-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from-date-day']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'appointed_at_year' and @type = 'number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='from-date-day']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>673d86d6-b710-4c21-b942-4793f4354a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appointed_at_year</value>
      <webElementGuid>eec42a39-3dd4-443c-a492-33a85e3ea4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>38a53aae-b042-4301-b70b-160ce07f36a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from-date-day']</value>
      <webElementGuid>ee3b9b6a-ac0b-4c0e-be2f-61e6fe590a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/form/fieldset/div/div/div/div/div/input</value>
      <webElementGuid>59b6fe21-3aae-4d18-b954-ecb94cfc1a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>fd1d9337-3394-4d8b-90f3-ff956f450e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'from-date-day' and @name = 'from_date_day' and @type = 'number']</value>
      <webElementGuid>f3e9438d-2bfe-4073-b0df-7482490f6164</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
