<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pricePaid</name>
   <tag></tag>
   <elementGuidId>c758bb52-b30d-49bb-b1aa-a2475f5f2441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#price_per_share</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='price_per_share']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Price paid&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc9a5bc7-a583-4792-b477-3c73424b930c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6c359be1-aadf-44ee-a10e-baa042b1bd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>price_per_share</value>
      <webElementGuid>b45d98e4-ca2e-414f-a1a5-651bdadff69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>860e5c69-2def-4021-86de-213a95f7e83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>price_per_share</value>
      <webElementGuid>46b06287-11dd-4599-af47-1dba036f7314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;price_per_share&quot;)</value>
      <webElementGuid>6bc5455b-79d0-4ec8-b416-6675ab254850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='price_per_share']</value>
      <webElementGuid>c3405b14-fc81-4bb4-814c-04192da24477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[2]/div/form/fieldset[2]/div[3]/div[2]/input</value>
      <webElementGuid>9317d19f-278d-47c1-9ca2-23143951db29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>2327f1a1-fed7-4369-bbd8-9c3f9b544874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'price_per_share' and @type = 'text' and @id = 'price_per_share']</value>
      <webElementGuid>0d6b4a80-766a-4804-a40c-1b1aaf7f11cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
