<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_shareAuthorisationSelectItem</name>
   <tag></tag>
   <elementGuidId>9faabd86-c72b-4bda-a72d-047ea6d3da25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#share_approval_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'option' and contains(@aria-label, 'Ordinary share pool 1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Share authorisation&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>59fa853d-08bb-4d5a-8f6c-9b71fc7cd6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e8618885-59cd-4a18-9189-2fabadebf06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Ordinary share pool 1</value>
      <webElementGuid>19846e75-574b-4353-918e-8638068d182b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
