<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_GS Auth share class</name>
   <tag></tag>
   <elementGuidId>068e8218-034b-4ed7-bf3b-a8246cbad18a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='share_class_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#share_class_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Share class&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6d598810-08af-48b8-a6fd-b8cf40150f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>94ba406b-1dc5-4fcd-a8af-d380c140cbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>share_class_id</value>
      <webElementGuid>16f9ab1a-d0d1-4592-9a45-7763b5fd6537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>share_class_id</value>
      <webElementGuid>4318caec-63e8-4215-80dd-691886ed7b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select…Ordinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)</value>
      <webElementGuid>218fd9a6-c392-40cc-8b02-226b54a371b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share_class_id&quot;)</value>
      <webElementGuid>9625c32d-be06-43b0-ae9d-0b5764d268e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='share_class_id']</value>
      <webElementGuid>5ebdbb62-4fa7-419f-b52f-73a649e3896b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='js-share-approval-form']/div[3]/select</value>
      <webElementGuid>98792328-081e-407b-bbf9-22190b34e126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share class'])[1]/following::select[1]</value>
      <webElementGuid>82a6f8f6-baa9-45a3-ba92-39978ab0040b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pool size'])[1]/following::select[1]</value>
      <webElementGuid>895182c3-5beb-4394-87c4-4f4eb83830f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolutions'])[2]/preceding::select[1]</value>
      <webElementGuid>b49fbf21-324f-4364-aef4-0714caf9febc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>88cef977-7388-4847-a3cb-668ef65b0fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'share_class_id' and @name = 'share_class_id' and (text() = 'Please select…Ordinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)' or . = 'Please select…Ordinary (voting) (£0.0001)Ordinary A (voting) (£0.0001)')]</value>
      <webElementGuid>ac3e8058-9632-4046-925f-cdd5bc3cb0d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
