<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Record an investment</name>
   <tag></tag>
   <elementGuidId>3381290e-1f11-4364-8179-2f235cf70ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-md.btn-outline-secondary.btn-not-submit.mb-0.v-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/section/div/div/div/div/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>566e37cf-7197-4e4f-8d60-d406453e2f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>c0bb198c-cd12-4908-9662-b7976e7b07cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.app.vestd.com/external-investment/create</value>
      <webElementGuid>57bca9fd-5c43-4fb8-af2a-0106fccee2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-md btn-outline-secondary btn-not-submit mb-0 v-btn</value>
      <webElementGuid>6baf5986-f8d3-4716-9a56-ea94662ab77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>link-button</value>
      <webElementGuid>1d989e02-eba2-4d6d-b771-087e793cc68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Record an investment</value>
      <webElementGuid>93020109-c708-4fb0-8dbe-0a7e4837e2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/section[@class=&quot;row my-4&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;card my-4&quot;]/div[@class=&quot;card-body text-muted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-xl-3&quot;]/div[@class=&quot;d-inline-block&quot;]/div[@class=&quot;d-inline-block&quot;]/a[@class=&quot;btn btn-md btn-outline-secondary btn-not-submit mb-0 v-btn&quot;]</value>
      <webElementGuid>58d78de3-1289-443a-a91f-d7a1f6c6bf3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/section/div/div/div/div/div[2]/div/div/a</value>
      <webElementGuid>f83e56b1-4520-4722-aae5-eba7f73da675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='invested'])[1]/following::a[1]</value>
      <webElementGuid>970d64de-e2cc-46fd-bd82-f7776f7ebc3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/following::a[1]</value>
      <webElementGuid>d155b063-d352-45da-b5a5-6b4c6948b1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get the most out of your dashboard'])[1]/preceding::a[1]</value>
      <webElementGuid>777819ca-8373-47cc-b398-d05046c8c301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Record an investment']/parent::*</value>
      <webElementGuid>b3f5bab1-67dd-43d0-97f2-a70d78560a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.app.vestd.com/external-investment/create')]</value>
      <webElementGuid>a2bc11e9-732c-4d98-bcbf-516d44dc40c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>9297ead6-7c9c-45f4-ad30-b3181723693a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.app.vestd.com/external-investment/create' and (text() = 'Record an investment' or . = 'Record an investment')]</value>
      <webElementGuid>31d306d4-87c7-4e79-8361-906aca600219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
