<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ul7KyLCn7tiEks2M</name>
   <tag></tag>
   <elementGuidId>083937bc-296e-4961-83c6-d769ba0ec663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div/input[@type='text' and @data-test-id='form-number-input'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ul7KyLCn7tiEks2M</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28e29a98-9201-424c-b076-f7f51ab84da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02679170-03c4-44b3-8ab0-3cea95d7cfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>7d261b82-4767-48ee-af7e-2a654741b92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>02c1d70f-81a7-4dcc-9ed9-1dedd2a85724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ul7KyLCn7tiEks2M</value>
      <webElementGuid>1918d362-bd3d-4e78-800f-fec013e6f9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>fe710299-cead-40c7-960d-c6f9949226af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ul7KyLCn7tiEks2M&quot;)</value>
      <webElementGuid>0bb34b49-5592-4aec-a150-e498d29f4661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ul7KyLCn7tiEks2M']</value>
      <webElementGuid>23b49623-1033-4e18-8ec4-daf828ac480d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/form/fieldset/div[2]/div[4]/div/div/input</value>
      <webElementGuid>6f1ca470-b276-4ae9-a087-263cd276dded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>d1628278-e50e-4db0-ad33-807874626468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ul7KyLCn7tiEks2M']</value>
      <webElementGuid>81234cf6-fe1e-4f00-b399-fe5a1e0bbbc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
