<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Ordinary A</name>
   <tag></tag>
   <elementGuidId>5a134989-32f2-44a8-8e70-32419facd53a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@aria-label='Ordinary A']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lqsNn8eUC0pcBijw-multiselect-option-178390</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>50aa6248-a35f-4b96-96c0-f6630e752602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-option is-pointed</value>
      <webElementGuid>9b773a11-b5d1-4c65-9dab-a929ac98887d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lqsNn8eUC0pcBijw-multiselect-option-178390</value>
      <webElementGuid>b94d257a-8e12-4575-ac2d-70faec65c609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d187bb73-2f3d-489b-b758-021997cd85c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Ordinary A</value>
      <webElementGuid>b411eedd-a0aa-4d45-b7fc-aa0f8a9638d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f1871861-9e09-4974-9091-da07430402dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pointed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d5bbdecc-0d7a-4ec3-8d25-bfa4e03d6a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ordinary A</value>
      <webElementGuid>eafa47cc-4444-4eaf-8c77-99b4ffd3b63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lqsNn8eUC0pcBijw-multiselect-option-178390&quot;)</value>
      <webElementGuid>8666408f-041b-4c1e-b0c4-27ce79c6a570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='lqsNn8eUC0pcBijw-multiselect-option-178390']</value>
      <webElementGuid>af7521ad-9873-48a0-af4b-4d0f7d387a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lqsNn8eUC0pcBijw-multiselect-options']/li[2]</value>
      <webElementGuid>7e1606fe-ec12-4c4f-8c5d-7d8f9992d9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[2]/following::li[1]</value>
      <webElementGuid>611b5519-7626-46e5-bfdf-dbe2249732f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[1]/following::li[2]</value>
      <webElementGuid>a4a68e20-f63b-4712-99a4-8ce7e55843fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordinary B'])[1]/preceding::li[1]</value>
      <webElementGuid>4f4eb801-08cd-4f8a-9d37-93ab5b5acc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/ul/li[2]</value>
      <webElementGuid>79ea2136-a553-42fe-a8f5-e023c1fae9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'lqsNn8eUC0pcBijw-multiselect-option-178390' and (text() = 'Ordinary A' or . = 'Ordinary A')]</value>
      <webElementGuid>5f5d8fe7-b603-494f-8991-580a8a37d9a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
