<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_employee2Data</name>
   <tag></tag>
   <elementGuidId>cba8ae78-a374-4687-9bdd-f8730738de78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12.pb-2 > div > div > div.col-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr[1]/following-sibling::tr[1]//div[normalize-space(text())='Employee']/following-sibling::div[1]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div[4]/div/div[2]/div/div/div[2]/div/div/div[4]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
