<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_include-deferred-shares</name>
   <tag></tag>
   <elementGuidId>020c4777-9bbc-4d4d-b3d0-9ab85f76144d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='L95fPejezWwDnpOu-multiselect-option-692094']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(contains(text(), 'Include deferred shares') or contains(., 'Include deferred shares'))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#L95fPejezWwDnpOu-multiselect-option-692094</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//li[@id='L95fPejezWwDnpOu-multiselect-option-692094']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7fb1dd15-3328-4830-a2d6-7e7550a6765e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-option is-pointed</value>
      <webElementGuid>9abe7dab-1551-449b-80f8-748ad8d549d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f4827770-0d1c-46a1-9e2c-e8b057c2b28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Include deferred shares</value>
      <webElementGuid>531c72f6-b13b-4276-b7dd-535d253acad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='L95fPejezWwDnpOu-multiselect-option-692094']</value>
      <webElementGuid>786d178c-7c14-42a9-b300-0e7a0fd09336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='L95fPejezWwDnpOu-multiselect-options']/li[2]</value>
      <webElementGuid>ad8933df-dbdf-4810-a162-2dbf9ff97ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[5]/following::li[1]</value>
      <webElementGuid>1579a27a-9465-44f7-a50d-c675d8c65879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select...'])[4]/following::li[2]</value>
      <webElementGuid>f2d7858b-45fe-4acd-bb9b-c38cfeef362d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barry Saunders (3,980 shares)'])[1]/preceding::li[1]</value>
      <webElementGuid>5fb1a362-b0a9-43c2-899c-8ca0d075690d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/ul/li[2]</value>
      <webElementGuid>a0265529-5abc-48d7-bc87-de8018fdfea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'L95fPejezWwDnpOu-multiselect-option-692094' and (text() = 'AdminSuper SP (999,980 shares)' or . = 'AdminSuper SP (999,980 shares)')]</value>
      <webElementGuid>8fc7f39c-ea7d-4703-92cd-4a8b382d5364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
