<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exercise price_exercise_price</name>
   <tag></tag>
   <elementGuidId>0d8549ad-cc95-47f1-bba4-d2fe56eb5255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exercise_price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exercise_price']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'form-control' and @data-test-id = 'form-number-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//input[@id='exercise_price']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7eeabd4-3c73-4188-b43b-f886e50ac750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>98e525af-3215-4663-90f4-fbe334ac085b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>792a4cd6-eda5-4824-85cf-a526fdc35846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exercise_price']</value>
      <webElementGuid>40b41cbd-309f-4037-bb28-7cf71493e203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[2]/div/form/fieldset/div/div[2]/input</value>
      <webElementGuid>295a38e0-1bf1-475d-b8a3-7c60631c9b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a9053ee1-2342-4834-b29e-be3e81eddca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'exercise_price' and @type = 'number' and @id = 'exercise_price']</value>
      <webElementGuid>580ab8fc-709c-4235-8cef-b439b4a8d42c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
