<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Grant date</name>
   <tag></tag>
   <elementGuidId>0d8b00dd-e0b4-4bca-9a14-d191605b06f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='grant_on_accept']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'grant_on_accept' and @name = 'grant_on_accept' and (text() = 'Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires' or . = 'Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#grant_on_accept</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//select[@id='grant_on_accept']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7c6bfeb1-c148-4087-8a46-5efafd76efb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0eab01c2-16d9-4e23-8f28-385cd4886e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grant_on_accept</value>
      <webElementGuid>ed68d480-83bc-484c-a36e-ac1cd7918190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>grant_on_accept</value>
      <webElementGuid>33cf78fb-3a8d-4568-97bd-2457aa508957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires</value>
      <webElementGuid>6d6d8f95-8625-4f89-bb0f-3ee7f7f7a268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grant_on_accept&quot;)</value>
      <webElementGuid>ea75be55-afd2-4cd3-be58-334865499f45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='grant_on_accept']</value>
      <webElementGuid>98ceae61-1fe1-43a0-8405-7cced858d62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[2]/div/form/fieldset[3]/div/select</value>
      <webElementGuid>48201ae0-8a7f-4a64-9b26-69136c71401c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When should the options be granted?'])[1]/following::select[1]</value>
      <webElementGuid>e86cc462-39c8-4b1b-8033-0c2d69ad5051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grant dates'])[1]/following::select[1]</value>
      <webElementGuid>51a43ead-ab8c-42e7-9887-65ef7b49a866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BADR'])[1]/preceding::select[1]</value>
      <webElementGuid>608395dd-4eb5-42f5-abd3-39fec24cb059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grant date - Day'])[1]/preceding::select[1]</value>
      <webElementGuid>ab4e51eb-3645-4756-8052-7d3a65e742cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/select</value>
      <webElementGuid>04f6b966-780f-44a3-93a1-677bcfad012f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'grant_on_accept' and @name = 'grant_on_accept' and (text() = 'Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires' or . = 'Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires')]</value>
      <webElementGuid>a521ee75-4a2d-437e-a4dd-6135d131c925</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
