<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_simulate-all</name>
   <tag></tag>
   <elementGuidId>76749876-fc86-410b-bc3d-e6ba84960c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vesting-type-all-nowvalue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vesting-type-until-nowvalue']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'form-check-input' and @type = 'radio' and @name = 'vesting_typevalue' and @id = 'vesting-type-all-nowvalue' and @value = 'all-now']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Vested until now&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e9cbff4-1d47-46f1-8177-345d276e08d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>afe3b8b4-b496-4b94-b9a6-12dbb2ce5cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>57a401f3-e63d-4fef-99dc-03e6bb74a5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vesting_typevalue</value>
      <webElementGuid>56131d8d-22dd-4714-81cc-049ca9d49c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vesting-type-all-nowvalue</value>
      <webElementGuid>c1594c21-6069-4690-838d-90179e7d0dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>all-now</value>
      <webElementGuid>a8a96e3f-cff4-4528-819e-8d84aa83a93a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vesting-type-until-nowvalue']</value>
      <webElementGuid>602010d6-8365-4114-ba0e-b80475607615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>1732c8ba-9ca7-48e1-a338-1ac1d44dd191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>584b4e17-5d9d-489b-aea9-8a06983c5578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'vesting_typevalue' and @id = 'vesting-type-until-nowvalue']</value>
      <webElementGuid>2f8cf5ca-704a-4142-94ff-0fa58d928dbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
