<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please selectExercisableExit only</name>
   <tag></tag>
   <elementGuidId>a8fc1dd7-353f-4121-8d77-4208a5250d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expiry-event</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expiry-event']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#expiry-event</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d33f046a-3a3d-41a2-b4cd-2b5fe0984a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1e592b18-c3f3-46dd-8563-3fbe0573ddcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry-event</value>
      <webElementGuid>a60509fa-d96d-42ec-8635-d0c2df3aa504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option_expiry_event</value>
      <webElementGuid>83ff7b48-45bb-4bf0-bb84-8f422f8cea5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectExercisableExit only</value>
      <webElementGuid>811bdd04-1bb9-46c1-bf9a-48c10efa5399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry-event&quot;)</value>
      <webElementGuid>4668f235-dc8d-4f4d-a4a5-af827c316c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expiry-event']</value>
      <webElementGuid>8c19cbb7-62b6-455d-9d4e-96a69cd2df55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[2]/div/form/fieldset/div[2]/select</value>
      <webElementGuid>b33cb64b-4727-4d35-b86e-30b9c9911524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exercise condition'])[1]/following::select[1]</value>
      <webElementGuid>251cce74-a9a9-41d2-9948-1f313093143d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='per share'])[1]/following::select[1]</value>
      <webElementGuid>bb44de57-a5dc-49e0-94d2-d4a6678729c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert to exercisable after'])[1]/preceding::select[1]</value>
      <webElementGuid>5a4d93e6-ace3-4d33-908e-65e1ebd89271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/preceding::select[2]</value>
      <webElementGuid>652e2032-e0ee-4311-8b60-82f1fe2a7311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/select</value>
      <webElementGuid>5a3dec71-4746-4893-be93-b98d11e8fa19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'expiry-event' and @name = 'option_expiry_event' and (text() = 'Please selectExercisableExit only' or . = 'Please selectExercisableExit only')]</value>
      <webElementGuid>c9cb3df1-909f-46f4-8f2c-9a307cfc9ce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
