<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Leaver-condition</name>
   <tag></tag>
   <elementGuidId>001b868f-d546-485c-a53d-bea44da462ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option_leaver_clause</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'option_leaver_clause' and @name = 'option_leaver_clause' and (text() = 'Please select oneKeep vested optionsAllow vested options to be exercisedLose everythingComplete discretion' or . = 'Please select oneKeep vested optionsAllow vested options to be exercisedLose everythingComplete discretion')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='option_leaver_clause']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//select[@id='option_leaver_clause']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9bf211b9-c763-4548-819f-0bf6ac6e630b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9f0c4a52-a603-4d8a-b05c-f81105c8961e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option_leaver_clause</value>
      <webElementGuid>16ed7c61-7e4b-4c45-b1f6-2b1c3aa1b300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option_leaver_clause</value>
      <webElementGuid>14054c89-c4f0-4932-ba0f-aa8ff30a6d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select oneKeep vested optionsAllow vested options to be exercisedLose everythingComplete discretion</value>
      <webElementGuid>5dc2ffda-38d0-4870-94fb-3620c3f9efdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option_leaver_clause&quot;)</value>
      <webElementGuid>c64f05f3-0d6a-4c93-92d0-42e9e0456ff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='option_leaver_clause']</value>
      <webElementGuid>103e3009-2726-45c0-b260-eb34c6d97d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[2]/div/form/fieldset[4]/div/select</value>
      <webElementGuid>00af105f-75e5-4a23-a5dc-f5ade35307bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee leaver clause'])[1]/following::select[1]</value>
      <webElementGuid>8c6befc6-2407-47d5-9786-633873b113b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good leaver / bad leaver'])[1]/following::select[1]</value>
      <webElementGuid>0efd72ef-fc02-407d-9d96-4a7112620229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep vested options'])[2]/preceding::select[1]</value>
      <webElementGuid>893132f2-804d-4917-a0a3-b6e535917726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow vested options to be exercised'])[2]/preceding::select[1]</value>
      <webElementGuid>d976bb17-4cd8-45a5-8903-48283ebf29cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/select</value>
      <webElementGuid>876df351-322a-440c-af18-53b97deee528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'option_leaver_clause' and @name = 'option_leaver_clause' and (text() = 'Please select oneKeep vested optionsAllow vested options to be exercisedLose everythingComplete discretion' or . = 'Please select oneKeep vested optionsAllow vested options to be exercisedLose everythingComplete discretion')]</value>
      <webElementGuid>c25569f4-61a9-4088-a536-a8e6f08173c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
