<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Exercise-condition</name>
   <tag></tag>
   <elementGuidId>a8fc1dd7-353f-4121-8d77-4208a5250d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expiry-event</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'expiry-event' and @name = 'option_expiry_event' and (text() = 'Please selectExercisableExit only' or . = 'Please selectExercisableExit only')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expiry-event']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//select[@id='expiry-event']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b1411d0e-b8ba-433b-89f8-7687e60ba420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d7552c03-6be1-469c-a1ab-5441180da30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry-event</value>
      <webElementGuid>49263efe-ea6f-49b5-a6f6-6605fcb9eda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option_expiry_event</value>
      <webElementGuid>9cbe3008-49d9-4e3e-996f-8f3c44897d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectExercisableExit only</value>
      <webElementGuid>35e24be7-d342-4a48-b4c1-c5afc90cbc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry-event&quot;)</value>
      <webElementGuid>3a991c03-8a6e-41b7-8dd6-47e1ca079f04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expiry-event']</value>
      <webElementGuid>7b32f321-09d8-4319-b80c-0073e58a9a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[2]/div/form/fieldset/div[2]/select</value>
      <webElementGuid>aac41a93-77cb-4bd1-884b-20b9be092155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exercise condition'])[1]/following::select[1]</value>
      <webElementGuid>97eb92b0-4ddf-4334-bb87-23868b9e3de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='per share'])[1]/following::select[1]</value>
      <webElementGuid>8597cba5-d623-470f-bf23-e511fb0bcc6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert to exercisable after'])[1]/preceding::select[1]</value>
      <webElementGuid>8dcc2782-1c2b-4d68-98c9-2e131e3a2c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/preceding::select[2]</value>
      <webElementGuid>3c311657-47f1-4252-92d1-4a340d819c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/select</value>
      <webElementGuid>4152c32c-dcb1-4a62-98ed-ab83dc9c616c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'expiry-event' and @name = 'option_expiry_event' and (text() = 'Please selectExercisableExit only' or . = 'Please selectExercisableExit only')]</value>
      <webElementGuid>e3eacbce-2d3f-409d-bb7d-6421da64dd06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
