<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select oneKeep vested options_6b824f</name>
   <tag></tag>
   <elementGuidId>001b868f-d546-485c-a53d-bea44da462ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option_leaver_clause</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'option_leaver_clause' and @name = 'option_leaver_clause' and (text() = 'Please select oneKeep vested optionsAllow vested options to be exercisedLose everythingComplete discretion' or . = 'Please select oneKeep vested optionsAllow vested options to be exercisedLose everythingComplete discretion')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='option_leaver_clause']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Employee leaver clause&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>33d74b26-a831-4f10-849a-f02829cd0175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f91fc1dd-d01c-4005-a270-52dc14527bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option_leaver_clause</value>
      <webElementGuid>088a0a7b-d5a4-44ca-981a-df3960a3627c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option_leaver_clause</value>
      <webElementGuid>10afd57b-807b-414f-8c51-ec0179883396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select oneKeep vested optionsAllow vested options to be exercisedLose everythingComplete discretion</value>
      <webElementGuid>a4a62767-c739-48f1-b68e-80ca214996d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option_leaver_clause&quot;)</value>
      <webElementGuid>1c80b8f4-8f8e-4935-a723-9e04fa12cb46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='option_leaver_clause']</value>
      <webElementGuid>39145e94-7332-419f-b4cb-2e2a5d5428dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[2]/div/form/fieldset[4]/div/select</value>
      <webElementGuid>b1daf5d1-dd64-4fc3-84c1-74b56e072f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee leaver clause'])[1]/following::select[1]</value>
      <webElementGuid>cf160f01-d258-40f5-9d9f-73250454d22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good leaver / bad leaver'])[1]/following::select[1]</value>
      <webElementGuid>58798ce6-7c71-48bd-9185-7d53a62d4cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep vested options'])[2]/preceding::select[1]</value>
      <webElementGuid>75432a20-d73b-4bfd-be51-188c19609ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow vested options to be exercised'])[2]/preceding::select[1]</value>
      <webElementGuid>1c9be5d1-8b88-4a56-9b3e-cd6cbc08140b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/select</value>
      <webElementGuid>824048e6-2c62-4b5c-9d78-4030ed0704c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'option_leaver_clause' and @name = 'option_leaver_clause' and (text() = 'Please select oneKeep vested optionsAllow vested options to be exercisedLose everythingComplete discretion' or . = 'Please select oneKeep vested optionsAllow vested options to be exercisedLose everythingComplete discretion')]</value>
      <webElementGuid>773623a4-0fb4-4238-b838-311e9a094b1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
