<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Grant all options on a specified dat_8fac1b</name>
   <tag></tag>
   <elementGuidId>0d8b00dd-e0b4-4bca-9a14-d191605b06f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grant_on_accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='grant_on_accept']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'grant_on_accept' and @name = 'grant_on_accept' and (text() = 'Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires' or . = 'Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//select[@id='grant_on_accept']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>177798a2-40e4-4535-ac9b-b1999239a458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fd0482ac-c7ff-40e7-b369-07d99ad1fd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grant_on_accept</value>
      <webElementGuid>dd1676ba-2055-44b2-8855-390a64cc7afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>grant_on_accept</value>
      <webElementGuid>38de50a5-a24e-49c8-9285-72be45ade74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires</value>
      <webElementGuid>5543bce0-2cfc-476e-b0a3-77db18b8c618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grant_on_accept&quot;)</value>
      <webElementGuid>46026e5d-72bb-4619-bf29-6d3833c8bb72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='grant_on_accept']</value>
      <webElementGuid>6b544d7f-67f0-4157-a97e-16b2092daec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[2]/div/form/fieldset[3]/div/select</value>
      <webElementGuid>7d76f43d-f6c6-4cf5-bb56-d84c80d7990f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When should the options be granted?'])[1]/following::select[1]</value>
      <webElementGuid>4e2869d7-095f-4aa1-a1fa-e8962745a027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grant dates'])[1]/following::select[1]</value>
      <webElementGuid>68dcb096-7a2b-41e6-ac0a-064acf7619b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BADR'])[1]/preceding::select[1]</value>
      <webElementGuid>d8a21063-5eed-4992-81f1-9e889ba75095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grant date - Day'])[1]/preceding::select[1]</value>
      <webElementGuid>97db39c1-df58-4e0b-8198-1bd0f1548550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/select</value>
      <webElementGuid>d5931c4e-df31-43a6-8a76-e85971d22da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'grant_on_accept' and @name = 'grant_on_accept' and (text() = 'Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires' or . = 'Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires')]</value>
      <webElementGuid>b338c07e-a5ea-4470-8ddc-3f6e744ee03f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
