<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Grant all options on a specified dat_8fac1b</name>
   <tag></tag>
   <elementGuidId>0d8b00dd-e0b4-4bca-9a14-d191605b06f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grant_on_accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='grant_on_accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;When should the options be granted?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>712e85f9-aa0e-46b6-b6b8-3eb4f1ed4926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ded39912-1a47-47bc-a578-a01ed5d53859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grant_on_accept</value>
      <webElementGuid>757b653b-e73a-4d71-9191-805f8ae86122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>grant_on_accept</value>
      <webElementGuid>ccceb00f-2930-4b4b-a56c-7f7666bfd92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires</value>
      <webElementGuid>4d01363a-ee9f-416d-9c9a-a90573058164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grant_on_accept&quot;)</value>
      <webElementGuid>1805303e-2bcc-405c-8910-2e9328fad321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='grant_on_accept']</value>
      <webElementGuid>f670c178-ae52-4ef9-9ba0-80f9242032a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[2]/div/form/fieldset[3]/div/select</value>
      <webElementGuid>45daeac1-4c2a-4ad8-a9f0-a894fc05b1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When should the options be granted?'])[1]/following::select[1]</value>
      <webElementGuid>3d1674da-ea28-43ca-b51a-ce8189aac2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grant dates'])[1]/following::select[1]</value>
      <webElementGuid>6c0d8f87-b07d-421c-af1a-015da5c008df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BADR'])[1]/preceding::select[1]</value>
      <webElementGuid>86bfc3e6-8ec5-49bf-bd0b-9066f852f7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grant date - Day'])[1]/preceding::select[1]</value>
      <webElementGuid>b03c6895-b624-4aaa-b82c-51c561047fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/select</value>
      <webElementGuid>6619d4c8-a94c-4aaf-90c5-a9537d31e667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'grant_on_accept' and @name = 'grant_on_accept' and (text() = 'Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires' or . = 'Grant all options on a specified date Grant as each option is accepted Grant the day before the valuation expires')]</value>
      <webElementGuid>c1b388a5-19bd-4ff0-bb7e-ad4f68d19589</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
