<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo</name>
   <tag></tag>
   <elementGuidId>523a43b9-2a20-4d82-9713-aa03fa6c7f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#time_based_vesting</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='time_based_vesting']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Use time based vesting?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>309b8e4c-6078-41e4-b9b4-2f2280c6f99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>940174d6-d356-4604-8ae5-cb7d1c1729be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>time_based_vesting</value>
      <webElementGuid>0778a611-02f0-4623-8980-e9d3f8482838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>time_based_vesting</value>
      <webElementGuid>1be91360-3a0a-40e7-898c-c78cc67c01c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>ad8e79f5-7506-4d6e-b6bb-4725dc1d9301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;time_based_vesting&quot;)</value>
      <webElementGuid>2bd523b5-5da5-4f98-b30e-c09136dec1e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='time_based_vesting']</value>
      <webElementGuid>f4742b26-2759-4e5e-8167-31ab452efccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[3]/div/form/fieldset[2]/div/select</value>
      <webElementGuid>aad46138-67d7-44ed-b789-80e118732923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use time based vesting?'])[1]/following::select[1]</value>
      <webElementGuid>cbb91b61-1093-488a-9a09-e1a91638d6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vesting'])[1]/following::select[1]</value>
      <webElementGuid>9361c5cc-330f-4806-8364-5fdff186316a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date'])[1]/preceding::select[1]</value>
      <webElementGuid>6b517565-ee2d-4d38-b1f0-e153f8373e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vesting duration'])[1]/preceding::select[1]</value>
      <webElementGuid>c9750baf-70c5-4e06-84f9-8769a2c2978f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/select</value>
      <webElementGuid>7ca18f99-81d8-4634-854d-730de585b278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'time_based_vesting' and @name = 'time_based_vesting' and (text() = 'YesNo' or . = 'YesNo')]</value>
      <webElementGuid>7c2c681c-3a94-4c5f-91e9-8761295a9e01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
