<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list-text_Options Exercised</name>
   <tag></tag>
   <elementGuidId>c4c50a85-7551-4ca8-831f-cc142024ea80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div[2]/div/div/div/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.report-guidelines > ul > li:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Options Exercised: See all options that were exercised during the period.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d93bb747-1796-4c23-94a5-ed7ce251d6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Options Exercised: See all options that were exercised during the period.</value>
      <webElementGuid>a2fcd0a9-50af-4ba9-a31b-f38d8ed378f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;report-guidelines&quot;]/ul[1]/li[3]</value>
      <webElementGuid>ba321286-2d5f-4e3f-ba2e-75f7da14b7d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div[2]/div/div/div/ul/li[3]</value>
      <webElementGuid>38291937-3c0d-4335-9ce4-f57bd16c5220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options Lapsed:'])[1]/following::li[1]</value>
      <webElementGuid>6f41adab-09be-402e-abe7-61c0d16c0b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='See all options that were exercised during the period.']/parent::*</value>
      <webElementGuid>0dd67252-417f-4cea-a39e-0afe9cf2019e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[3]</value>
      <webElementGuid>024f0b84-ab2d-4b17-baf1-dd3409b5e4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Options Exercised: See all options that were exercised during the period.' or . = 'Options Exercised: See all options that were exercised during the period.')]</value>
      <webElementGuid>e6a06254-e4b5-4972-a93d-f932e03d94f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
