<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list-text_Options Lapsed</name>
   <tag></tag>
   <elementGuidId>f5665528-ba08-4129-87fc-6780c4a6cca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div[2]/div/div/div/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.report-guidelines > ul > li:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Options Lapsed: View all options that lapsed during the period.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1981e42c-f1fa-4747-9093-112ea6c0d83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Options Lapsed: View all options that lapsed during the period.</value>
      <webElementGuid>9a3823e1-378b-4fcb-83a5-0b484564d1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;report-guidelines&quot;]/ul[1]/li[2]</value>
      <webElementGuid>c00e44f2-2257-447e-9cb7-f23675c92e38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div[2]/div/div/div/ul/li[2]</value>
      <webElementGuid>ca03b67e-ff1b-44e4-ad58-083919fe2f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options Vested:'])[1]/following::li[1]</value>
      <webElementGuid>f6d8c52a-098b-471d-ae6b-27c5229374b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View all options that lapsed during the period.']/parent::*</value>
      <webElementGuid>8e9f3acf-91f8-44c9-8045-1cd78b84d73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[2]</value>
      <webElementGuid>ad604d85-079e-4576-a7fc-06ed2ddc77ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Options Lapsed: View all options that lapsed during the period.' or . = 'Options Lapsed: View all options that lapsed during the period.')]</value>
      <webElementGuid>0c7131ae-0a32-4b54-adac-00e72a360adb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
