<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_10.00</name>
   <tag></tag>
   <elementGuidId>f0fd381d-8c41-4953-a97d-2116f1cbad16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/div[3]/div/div/div/table/tbody/tr[4]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;£10.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>acb20dfe-f2ac-4488-8191-e5afbd27c152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                £10.00
                            </value>
      <webElementGuid>a81a7b38-1119-4806-b554-920b35235338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;card mb-4&quot;]/div[@class=&quot;card-body bg-light&quot;]/table[@class=&quot;table table-sm table-striped border mb-4 mt-1&quot;]/tbody[1]/tr[4]/td[1]</value>
      <webElementGuid>727a9de8-fa52-471c-94a5-580f9950b475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div[3]/div/div/div/table/tbody/tr[4]/td</value>
      <webElementGuid>e0f63059-602c-4490-bebb-31501670d5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total price paid'])[1]/following::td[1]</value>
      <webElementGuid>8906d79c-242a-487d-a1ba-21940f75737d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£1.00 per share'])[1]/following::td[1]</value>
      <webElementGuid>e82fc622-a7f5-41f2-9fc6-b5698422cba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date agreed / issuance date'])[1]/preceding::td[1]</value>
      <webElementGuid>1d4f45c7-6194-4cbd-b859-62d8473bc22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/preceding::td[2]</value>
      <webElementGuid>e11b5f17-d653-4682-ab0c-38f442b4fc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='£10.00']/parent::*</value>
      <webElementGuid>e663dea4-090d-4371-897d-cd1c71c09a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td</value>
      <webElementGuid>4ed7d5b8-0795-4ec4-a2f5-f71f6fcf7061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                £10.00
                            ' or . = '
                                £10.00
                            ')]</value>
      <webElementGuid>af925576-bb8b-428b-b84b-a02b4925c633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
