<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Stock transfer</name>
   <tag></tag>
   <elementGuidId>7f20d73b-dc30-4c52-b8a9-c8d88666ac86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.even > td > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr[2]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Stock transfer&quot;s] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57568f3b-1342-4fb4-bc1b-f3ee1b66ee89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.app.vestd.com/company/50934/stock-transfer/1089</value>
      <webElementGuid>43cf13dc-5288-4dea-9c08-283733c5c28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stock transfer</value>
      <webElementGuid>2f644ab1-8efb-4ae4-9706-e44722ca68e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[1]/a[1]</value>
      <webElementGuid>256867d5-e053-4ad9-9c50-274e4199f8c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr[2]/td/a</value>
      <webElementGuid>c0222de0-e1e2-4746-aef1-33ad13d24a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Stock transfer')])[3]</value>
      <webElementGuid>fe4c5556-ef8d-4d46-922c-94115ca25031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[2]/following::a[1]</value>
      <webElementGuid>fe1d075e-22fa-4f1d-999b-3a5abf69b91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incorporation'])[2]/following::a[1]</value>
      <webElementGuid>9c241e0b-d78d-459e-a847-b91ec244ee3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordinary (voting)'])[2]/preceding::a[1]</value>
      <webElementGuid>6ba51710-ee54-474b-85a1-93d4bf4187fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£1.00'])[2]/preceding::a[2]</value>
      <webElementGuid>706b7a08-da27-40e1-862b-5b7bd604b113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.app.vestd.com/company/50934/stock-transfer/1089')]</value>
      <webElementGuid>6d807f5a-87f1-4261-9820-426b1f41aafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/a</value>
      <webElementGuid>712fc75b-4508-4a93-aebe-e556102a4436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.app.vestd.com/company/50934/stock-transfer/1089' and (text() = 'Stock transfer' or . = 'Stock transfer')]</value>
      <webElementGuid>8ee2b5e3-7030-460f-8c44-4aee128d4248</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
