<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to your dashboard</name>
   <tag></tag>
   <elementGuidId>4903138a-f82f-4c8f-b280-b0a20f6f8d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/div/div/div/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mega-dropdown-holder.ml-2 > button.btn.btn-outline-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>942055b5-9304-4629-ad1f-fa3d1727db32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-secondary</value>
      <webElementGuid>c484ef30-69d9-4381-b6a6-1ad781918ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>0de9a6e8-6dca-4646-8ddf-71b7f8f0ab18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63670d92-d783-40e6-af3a-ea1c82a1c624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3ebfbdd2-1d1d-4d66-80b1-05c49a063110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to your dashboard </value>
      <webElementGuid>4a635e1a-8431-422d-8315-928c2d616fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex justify-content-between mt-2 mb-3 flex-wrap&quot;]/div[@class=&quot;d-flex justify-content-end flex-wrap&quot;]/div[@class=&quot;mega-dropdown-holder ml-2&quot;]/button[@class=&quot;btn btn-outline-secondary&quot;]</value>
      <webElementGuid>0a566f02-5806-4f08-ac10-c6e5ff45053c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/div/div[2]/div/button</value>
      <webElementGuid>5072b836-8237-4e79-bcdf-4bc994be24b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::button[2]</value>
      <webElementGuid>c7cfd866-4fc7-42a6-9d13-95ba1556dd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to your dashboard']/parent::*</value>
      <webElementGuid>963dc3bd-4c0f-4be7-986a-8d007aba777c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>0b67c6a5-ee00-4db7-a44c-16b491b45a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add to your dashboard ' or . = 'Add to your dashboard ')]</value>
      <webElementGuid>11ba0ad8-89d5-4492-935d-aaa8ae7f1a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
