<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_total-price-paid</name>
   <tag></tag>
   <elementGuidId>a1dd081e-2efa-46de-8034-adc37d3fd2df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type = 'text' and @data-test-id = 'form-number-input' and @class = 'form-control'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OGCIcoyvb2D3FXd2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'OGCIcoyvb2D3FXd2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9381f93c-398c-44f8-bf3b-00545730b77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd669a8e-798a-4e16-b3c6-7ebb139661fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>form-number-input</value>
      <webElementGuid>0cff263b-4331-4f83-b4e9-3fda0e36574d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a6e39fc5-6f48-4d62-b2a7-5652b9c2086f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OGCIcoyvb2D3FXd2</value>
      <webElementGuid>0c2ec658-a7fc-4a3a-8ac1-c3d4c906cdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>df7e2d78-6c20-459b-b3c4-94b430b7dcca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OGCIcoyvb2D3FXd2&quot;)</value>
      <webElementGuid>1bb850f9-2e53-4d8d-8b16-2c49b43d520d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OGCIcoyvb2D3FXd2']</value>
      <webElementGuid>a786a5e4-1016-451d-a50a-c8224b71a725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/div/div/form/fieldset/div/div[6]/div/div/input</value>
      <webElementGuid>8289c11e-e912-4c98-9ea8-702dc68be1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>13e36ae1-b291-40fc-a455-8f5fb5bd5533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'OGCIcoyvb2D3FXd2']</value>
      <webElementGuid>3f75d9bc-49e4-40cf-878a-ed5cebf26b03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
