<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select the option agreement under whi_3b3a6b</name>
   <tag></tag>
   <elementGuidId>01cb70f3-6a8f-4cce-99ff-830bca892508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='m1mH6OIRLvqmQIqp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#m1mH6OIRLvqmQIqp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1703c09b-f00c-42b6-bce4-d7b31265ca46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ccb10b4-6d2f-4b54-9c1b-40f1cd72aafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-search</value>
      <webElementGuid>1e0818fe-b429-4536-9661-1efd2b9ef1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m1mH6OIRLvqmQIqp</value>
      <webElementGuid>bba74895-65e3-425d-93ad-20e55527d10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>m1mH6OIRLvqmQIqp-multiselect-options</value>
      <webElementGuid>9068b6c8-e49d-4cae-bb58-eea39a2d6edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7bba5b2c-12d0-455e-bc07-1210408f3807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46f65247-1b42-40b4-9412-9e81b29412f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>d2e1b667-8a3f-47bf-81bd-f856c0d21c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>m1mH6OIRLvqmQIqp-assist</value>
      <webElementGuid>1a737383-2eeb-40b7-8dc4-c79d63a9615f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m1mH6OIRLvqmQIqp&quot;)</value>
      <webElementGuid>f7687c7a-ce72-49db-96d5-f69df436998e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='m1mH6OIRLvqmQIqp']</value>
      <webElementGuid>89fd8765-693c-41e2-883e-17118cc2b43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='select-form']/fieldset/div/div[2]/div/div/div/input</value>
      <webElementGuid>ed24d638-11f0-446e-8231-15c78f0a63b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>40671902-127c-4c1f-9215-e1940af2e17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'm1mH6OIRLvqmQIqp']</value>
      <webElementGuid>41f1fa06-7f78-44a4-9fa9-79d0f8ee9f70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
